/** Generated from the owner's drawings (nuts, washers, pins, plugs, buffers, wear plates): one render each,
 *  `/photos/parca/<file>-vitrin-01` (and `-yan-01` for plates and buffers). Names come from the drawing titles (`kind`), never part numbers. */
import type { PartRender } from './photos';

export interface SmallPart {
  make: string;
  model: string;
  file: string;
  kind: NonNullable<PartRender['kind']>;
  variant?: PartRender['variant'];
}

export const SMALL_PARTS: Record<
  'saplama' | 'kama' | 'burc' | 'asinma-plakasi' | 'akumulator',
  readonly SmallPart[]
> = {
  saplama: [
    { make: 'Rammer', model: 'E64', file: 'somun-rammer-e64-tie-rod-nut', kind: 'tieRodNut' },
    { make: 'Rammer', model: 'E66', file: 'somun-rammer-e66-tie-rod-nut', kind: 'tieRodNut' },
    {
      make: 'Rammer',
      model: 'E66',
      file: 'somun-rammer-e66-tie-rod-nut-new-type',
      kind: 'tieRodNut',
      variant: 'newType',
    },
    { make: 'Rammer', model: 'G80', file: 'somun-rammer-g80-tie-rod-nut', kind: 'tieRodNut' },
    { make: 'Rammer', model: 'S25', file: 'somun-rammer-s25-tie-rod-nut', kind: 'tieRodNut' },
    { make: 'Rammer', model: 'S25', file: 'pul-rammer-s25-tie-rod-washer', kind: 'tieRodWasher' },
    { make: 'Rammer', model: 'S84', file: 'somun-rammer-s84-tie-rod-nut', kind: 'tieRodNut' },
    { make: 'MTB', model: '150', file: 'somun-mtb-150-tie-rod-nut', kind: 'tieRodNut' },
    { make: 'MTB', model: '210 II', file: 'somun-mtb-210-ii-tie-rod-nut', kind: 'tieRodNut' },
    { make: 'Krupp', model: 'HM 1500', file: 'pim-krupp-hm-1500-body-dowel', kind: 'bodyDowel' },
    { make: 'Krupp', model: 'HM 1500', file: 'somun-krupp-hm-1500-tie-rod-nut', kind: 'tieRodNut' },
    {
      make: 'Krupp',
      model: 'HM 1500',
      file: 'pul-krupp-hm-1500-tie-rod-washer',
      kind: 'tieRodWasher',
    },
    { make: 'Krupp', model: 'HM 560', file: 'somun-krupp-hm-560-tie-rod-nut', kind: 'tieRodNut' },
    {
      make: 'Krupp',
      model: 'HM 560',
      file: 'pul-krupp-hm-560-tie-rod-washer',
      kind: 'tieRodWasher',
    },
    { make: 'Krupp', model: 'HM 720', file: 'pul-krupp-hm-720-tie-rod-bush', kind: 'tieRodBush' },
    {
      make: 'Krupp',
      model: 'HM 720',
      file: 'somun-krupp-hm-720-tie-rod-lower-nut',
      kind: 'tieRodLowerNut',
    },
    {
      make: 'Krupp',
      model: 'HM 720',
      file: 'somun-krupp-hm-720-tie-rod-upper-nut',
      kind: 'tieRodUpperNut',
    },
    {
      make: 'Krupp',
      model: 'HM 720',
      file: 'pul-krupp-hm-720-tie-rod-washer',
      kind: 'tieRodWasher',
    },
    { make: 'Krupp', model: 'HM 960', file: 'pul-krupp-hm-960-tie-rod-bush', kind: 'tieRodBush' },
    {
      make: 'Krupp',
      model: 'HM 960',
      file: 'somun-krupp-hm-960-tie-rod-lower-nut',
      kind: 'tieRodLowerNut',
    },
    {
      make: 'Krupp',
      model: 'HM 960',
      file: 'somun-krupp-hm-960-tie-rod-upper-nut',
      kind: 'tieRodUpperNut',
    },
    {
      make: 'Krupp',
      model: 'HM 960',
      file: 'pul-krupp-hm-960-tie-rod-washer',
      kind: 'tieRodWasher',
    },
    {
      make: 'Krupp',
      model: 'HM 960',
      file: 'pul-krupp-hm-960-tie-rod-washer-new-type',
      kind: 'tieRodWasher',
      variant: 'newType',
    },
    {
      make: 'Soosan',
      model: 'SB121 TS-P',
      file: 'somun-soosan-sb121-ts-p-tie-rod-lower-nut-new-type',
      kind: 'tieRodLowerNut',
      variant: 'newType',
    },
    {
      make: 'Soosan',
      model: 'SB121 TS-P',
      file: 'somun-soosan-sb121-ts-p-tie-rod-lower-nut-round-nut',
      kind: 'tieRodLowerNut',
      variant: 'roundShape',
    },
    {
      make: 'Soosan',
      model: 'SB121 TS-P',
      file: 'somun-soosan-sb121-ts-p-tie-rod-lower-nut-tri-nut',
      kind: 'tieRodLowerNut',
      variant: 'triLobe',
    },
    {
      make: 'Soosan',
      model: 'SB121 TS-P',
      file: 'somun-soosan-sb121-ts-p-tie-rod-upper-nut',
      kind: 'tieRodUpperNut',
    },
    {
      make: 'Soosan',
      model: 'SB121 TS-P',
      file: 'pul-soosan-sb121-ts-p-tie-rod-washer',
      kind: 'tieRodWasher',
    },
    {
      make: 'Montabert',
      model: 'BRH 501',
      file: 'somun-montabert-brh-501-tie-rod-nut',
      kind: 'tieRodNut',
    },
    {
      make: 'Montabert',
      model: 'BRV 32',
      file: 'somun-montabert-brv-32-tie-rod-nut',
      kind: 'tieRodNut',
    },
    {
      make: 'Furukawa',
      model: 'F22',
      file: 'somun-furukawa-f22-tie-rod-lower-nut',
      kind: 'tieRodLowerNut',
    },
    {
      make: 'Furukawa',
      model: 'F22',
      file: 'somun-furukawa-f22-tie-rod-upper-nut',
      kind: 'tieRodUpperNut',
    },
    {
      make: 'Furukawa',
      model: 'HB20G',
      file: 'pul-furukawa-hb20g-side-bolt-washer',
      kind: 'sideBoltWasher',
    },
    {
      make: 'Furukawa',
      model: 'HB20G',
      file: 'pul-furukawa-hb20g-side-bolt-washer-new-type',
      kind: 'sideBoltWasher',
      variant: 'newType',
    },
    {
      make: 'Furukawa',
      model: 'HB20G',
      file: 'somun-furukawa-hb20g-tie-rod-lower-nut',
      kind: 'tieRodLowerNut',
    },
    {
      make: 'Furukawa',
      model: 'HB20G',
      file: 'somun-furukawa-hb20g-tie-rod-lower-nut-old-type',
      kind: 'tieRodLowerNut',
      variant: 'oldType',
    },
    {
      make: 'Furukawa',
      model: 'HB20G',
      file: 'somun-furukawa-hb20g-tie-rod-upper-nut',
      kind: 'tieRodUpperNut',
    },
    {
      make: 'Furukawa',
      model: 'HB20G',
      file: 'somun-furukawa-hb20g-tie-rod-upper-nut-old-type',
      kind: 'tieRodUpperNut',
      variant: 'oldType',
    },
    {
      make: 'Furukawa',
      model: 'HB20G',
      file: 'pul-furukawa-hb20g-tie-rod-washer',
      kind: 'tieRodWasher',
    },
    {
      make: 'Furukawa',
      model: 'HB30G',
      file: 'somun-furukawa-hb30g-tie-rod-lower-nut',
      kind: 'tieRodLowerNut',
    },
    {
      make: 'Furukawa',
      model: 'HB30G',
      file: 'somun-furukawa-hb30g-tie-rod-lower-nut-old-type',
      kind: 'tieRodLowerNut',
      variant: 'oldType',
    },
    {
      make: 'Furukawa',
      model: 'HB30G',
      file: 'somun-furukawa-hb30g-tie-rod-upper-nut',
      kind: 'tieRodUpperNut',
    },
    {
      make: 'Furukawa',
      model: 'HB30G',
      file: 'somun-furukawa-hb30g-tie-rod-upper-nut-old-type',
      kind: 'tieRodUpperNut',
      variant: 'oldType',
    },
    {
      make: 'Furukawa',
      model: 'HB30G',
      file: 'pul-furukawa-hb30g-tie-rod-washer',
      kind: 'tieRodWasher',
    },
    {
      make: 'Furukawa',
      model: 'HB30G',
      file: 'pul-furukawa-hb30g-tie-rod-washer-old-type',
      kind: 'tieRodWasher',
      variant: 'oldType',
    },
  ],
  kama: [
    {
      make: 'Rammer',
      model: 'G80',
      file: 'pim-rammer-g80-key-pin-retainer',
      kind: 'keyPinRetainer',
    },
    { make: 'Rammer', model: 'G80', file: 'pul-rammer-g80-key-pin-washer', kind: 'keyPinWasher' },
    {
      make: 'Rammer',
      model: 'S84',
      file: 'pim-rammer-s84-retainer-lock-pin',
      kind: 'retainerLockPin',
    },
    { make: 'MTB', model: '210', file: 'pim-mtb-210-key-pin-holder', kind: 'keyPinHolder' },
    { make: 'MTB', model: '210', file: 'pim-mtb-210-retainer-lock-pin', kind: 'retainerLockPin' },
    { make: 'MTB', model: '210 II', file: 'tapa-mtb-210-ii-key-pin-plug', kind: 'keyPinPlug' },
    { make: 'MTB', model: '210 II', file: 'pim-mtb-210-ii-retainer-pin', kind: 'retainerPin' },
    {
      make: 'Krupp',
      model: 'HM 720',
      file: 'pim-krupp-hm-720-key-pin-rubber',
      kind: 'keyPinRubber',
    },
    {
      make: 'Krupp',
      model: 'HM 720',
      file: 'pim-krupp-hm-720-retainer-pin',
      kind: 'retainerPin',
      variant: 'oldType',
    },
    {
      make: 'Montabert',
      model: 'BRV 32',
      file: 'pim-montabert-brv-32-lower-retainer-pin',
      kind: 'lowerRetainerPin',
    },
    {
      make: 'Montabert',
      model: 'BRV 32',
      file: 'pim-montabert-brv-32-retainer-pin',
      kind: 'retainerPin',
    },
    {
      make: 'Montabert',
      model: 'BRV 32',
      file: 'pim-montabert-brv-32-spring-pin',
      kind: 'springPin',
    },
    { make: 'Furukawa', model: 'F22', file: 'tapa-furukawa-f22-key-pin-plug', kind: 'keyPinPlug' },
  ],
  burc: [
    {
      make: 'Rammer',
      model: 'E64',
      file: 'pim-rammer-e64-tool-bushing-pin',
      kind: 'toolBushingPin',
    },
    {
      make: 'Rammer',
      model: 'E66',
      file: 'pim-rammer-e66-tool-bushing-pin',
      kind: 'toolBushingPin',
    },
    {
      make: 'Rammer',
      model: 'G80',
      file: 'pim-rammer-g80-tool-bushing-pin',
      kind: 'toolBushingPin',
    },
    {
      make: 'Rammer',
      model: 'S25',
      file: 'pim-rammer-s25-upper-bushing-pin',
      kind: 'upperBushingPin',
    },
    {
      make: 'Rammer',
      model: 'S84',
      file: 'pim-rammer-s84-tool-bushing-pin',
      kind: 'toolBushingPin',
    },
    { make: 'MTB', model: '210', file: 'pim-mtb-210-tool-bushing-pin', kind: 'toolBushingPin' },
    {
      make: 'MTB',
      model: '210 II',
      file: 'pim-mtb-210-ii-tool-bushing-pin',
      kind: 'toolBushingPin',
    },
    {
      make: 'MTB',
      model: '210 II',
      file: 'tapa-mtb-210-ii-tool-bushing-pin-plug',
      kind: 'toolBushingPinPlug',
    },
    {
      make: 'MTB',
      model: '210 II',
      file: 'pim-mtb-210-ii-upper-bushing-pin-no1',
      kind: 'upperBushingPin',
      variant: 'no1',
    },
    {
      make: 'MTB',
      model: '210 II',
      file: 'pim-mtb-210-ii-upper-bushing-pin-no2',
      kind: 'upperBushingPin',
      variant: 'no2',
    },
    {
      make: 'Krupp',
      model: 'HM 720',
      file: 'pim-krupp-hm-720-tool-upper-pin',
      kind: 'toolUpperPin',
      variant: 'oldType',
    },
    {
      make: 'Soosan',
      model: 'SB121 TS-P',
      file: 'pim-soosan-sb121-ts-p-tool-bushing-pin',
      kind: 'toolBushingPin',
    },
    {
      make: 'Montabert',
      model: 'BRH 501',
      file: 'pim-montabert-brh-501-tool-bushing-pin',
      kind: 'toolBushingPin',
    },
    {
      make: 'Montabert',
      model: 'BRH 501',
      file: 'tapa-montabert-brh-501-tool-bushing-pin-plug',
      kind: 'toolBushingPinPlug',
    },
    {
      make: 'Montabert',
      model: 'BRV 32',
      file: 'pim-montabert-brv-32-tool-bushing-pin',
      kind: 'toolBushingPin',
    },
    {
      make: 'Montabert',
      model: 'BRV 32',
      file: 'pim-montabert-brv-32-tool-bushing-pin-retainer',
      kind: 'toolBushingPinRetainer',
    },
    {
      make: 'Furukawa',
      model: 'F22',
      file: 'pim-furukawa-f22-tool-bushing-pin',
      kind: 'toolBushingPin',
    },
    {
      make: 'Furukawa',
      model: 'F22',
      file: 'tapa-furukawa-f22-tool-bushing-pin-plug',
      kind: 'toolBushingPinPlug',
    },
    {
      make: 'Furukawa',
      model: 'F22',
      file: 'pim-furukawa-f22-upper-bushing-pin',
      kind: 'upperBushingPin',
    },
    {
      make: 'Furukawa',
      model: 'F22',
      file: 'tapa-furukawa-f22-upper-bushing-pin-plug',
      kind: 'upperBushingPinPlug',
    },
    {
      make: 'Furukawa',
      model: 'HB20G',
      file: 'pim-furukawa-hb20g-tool-bushing-pin',
      kind: 'toolBushingPin',
    },
    {
      make: 'Furukawa',
      model: 'HB30G',
      file: 'pim-furukawa-hb30g-key-upper-pin',
      kind: 'keyUpperPin',
    },
    {
      make: 'Furukawa',
      model: 'HB30G',
      file: 'pim-furukawa-hb30g-tool-bushing-pin',
      kind: 'toolBushingPin',
    },
  ],
  'asinma-plakasi': [
    {
      make: 'Rammer',
      model: 'E64',
      file: 'asinma-rammer-e64-all-round-wear-plate',
      kind: 'allRoundWearPlate',
    },
    { make: 'Rammer', model: 'E64', file: 'takoz-rammer-e64-side-buffer', kind: 'sideBuffer' },
    { make: 'Rammer', model: 'E64', file: 'takoz-rammer-e64-top-buffer', kind: 'topBuffer' },
    { make: 'Rammer', model: 'E66', file: 'takoz-rammer-e66-top-buffer', kind: 'topBuffer' },
    {
      make: 'Rammer',
      model: 'E66',
      file: 'takoz-rammer-e66-top-buffer-city',
      kind: 'topBuffer',
      variant: 'city',
    },
    { make: 'Rammer', model: 'G80', file: 'takoz-rammer-g80-side-buffer', kind: 'sideBuffer' },
    {
      make: 'Rammer',
      model: 'G80',
      file: 'takoz-rammer-g80-side-buffer-pu',
      kind: 'sideBuffer',
      variant: 'pu',
    },
    { make: 'Rammer', model: 'G80', file: 'takoz-rammer-g80-top-buffer', kind: 'topBuffer' },
    {
      make: 'Rammer',
      model: 'G80',
      file: 'asinma-rammer-g80-wear-plate-no1',
      kind: 'wearPlate',
      variant: 'no1',
    },
    {
      make: 'Rammer',
      model: 'G80',
      file: 'asinma-rammer-g80-wear-plate-no2',
      kind: 'wearPlate',
      variant: 'no2',
    },
    {
      make: 'Rammer',
      model: 'G80',
      file: 'asinma-rammer-g80-wear-plate-no3',
      kind: 'wearPlate',
      variant: 'no3',
    },
    {
      make: 'Rammer',
      model: 'G80',
      file: 'asinma-rammer-g80-wear-plate-no4',
      kind: 'wearPlate',
      variant: 'no4',
    },
    { make: 'Rammer', model: 'S84', file: 'takoz-rammer-s84-side-buffer', kind: 'sideBuffer' },
    {
      make: 'Rammer',
      model: 'S84',
      file: 'takoz-rammer-s84-top-buffer-pu',
      kind: 'topBuffer',
      variant: 'pu',
    },
    {
      make: 'Rammer',
      model: 'S84',
      file: 'takoz-rammer-s84-top-buffer-rubber',
      kind: 'topBuffer',
      variant: 'rubber',
    },
    { make: 'MTB', model: '150', file: 'takoz-mtb-150-side-buffer', kind: 'sideBuffer' },
    { make: 'MTB', model: '150', file: 'takoz-mtb-150-top-buffer', kind: 'topBuffer' },
    { make: 'MTB', model: '150', file: 'takoz-mtb-150-top-buffer-plate', kind: 'topBufferPlate' },
    { make: 'MTB', model: '210', file: 'takoz-mtb-210-top-buffer', kind: 'topBuffer' },
    { make: 'MTB', model: '210', file: 'takoz-mtb-210-top-buffer-plate', kind: 'topBufferPlate' },
    {
      make: 'MTB',
      model: '210',
      file: 'takoz-mtb-210-top-buffer-plate-new-type',
      kind: 'topBufferPlate',
      variant: 'newType',
    },
    { make: 'MTB', model: '210 II', file: 'takoz-mtb-210-ii-bottom-buffer', kind: 'bottomBuffer' },
    {
      make: 'MTB',
      model: '210 II',
      file: 'asinma-mtb-210-ii-front-wear-plate',
      kind: 'frontWearPlate',
    },
    { make: 'MTB', model: '210 II', file: 'takoz-mtb-210-ii-side-buffer', kind: 'sideBuffer' },
    {
      make: 'MTB',
      model: '210 II',
      file: 'asinma-mtb-210-ii-side-wear-plate',
      kind: 'sideWearPlate',
    },
    {
      make: 'MTB',
      model: '210 II',
      file: 'asinma-mtb-210-ii-top-wear-plate',
      kind: 'topWearPlate',
    },
    {
      make: 'Krupp',
      model: 'HM 1500',
      file: 'takoz-krupp-hm-1500-side-buffer',
      kind: 'sideBuffer',
    },
    {
      make: 'Krupp',
      model: 'HM 1500',
      file: 'asinma-krupp-hm-1500-side-wear-plate',
      kind: 'sideWearPlate',
    },
    { make: 'Krupp', model: 'HM 1500', file: 'takoz-krupp-hm-1500-top-buffer', kind: 'topBuffer' },
    { make: 'Krupp', model: 'HM 560', file: 'takoz-krupp-hm-560-side-buffer', kind: 'sideBuffer' },
    { make: 'Krupp', model: 'HM 560', file: 'takoz-krupp-hm-560-top-buffer', kind: 'topBuffer' },
    { make: 'Krupp', model: 'HM 720', file: 'takoz-krupp-hm-720-side-buffer', kind: 'sideBuffer' },
    { make: 'Krupp', model: 'HM 720', file: 'takoz-krupp-hm-720-top-buffer', kind: 'topBuffer' },
    { make: 'Krupp', model: 'HM 960', file: 'takoz-krupp-hm-960-side-buffer', kind: 'sideBuffer' },
    { make: 'Krupp', model: 'HM 960', file: 'takoz-krupp-hm-960-top-buffer', kind: 'topBuffer' },
    {
      make: 'Soosan',
      model: 'SB121 TS-P',
      file: 'takoz-soosan-sb121-ts-p-bottom-buffer',
      kind: 'bottomBuffer',
    },
    {
      make: 'Soosan',
      model: 'SB121 TS-P',
      file: 'takoz-soosan-sb121-ts-p-bottom-buffer-plate',
      kind: 'bottomBufferPlate',
    },
    {
      make: 'Soosan',
      model: 'SB121 TS-P',
      file: 'takoz-soosan-sb121-ts-p-buffer-guide',
      kind: 'bufferGuide',
    },
    {
      make: 'Soosan',
      model: 'SB121 TS-P',
      file: 'takoz-soosan-sb121-ts-p-top-buffer',
      kind: 'topBuffer',
    },
    {
      make: 'Soosan',
      model: 'SB121 TS-P',
      file: 'takoz-soosan-sb121-ts-p-top-buffer-type-y',
      kind: 'topBuffer',
      variant: 'typeY',
    },
    {
      make: 'Montabert',
      model: 'BRH 501',
      file: 'takoz-montabert-brh-501-side-buffer',
      kind: 'sideBuffer',
    },
    {
      make: 'Montabert',
      model: 'BRH 501',
      file: 'takoz-montabert-brh-501-top-buffer',
      kind: 'topBuffer',
    },
    {
      make: 'Montabert',
      model: 'BRV 32',
      file: 'takoz-montabert-brv-32-side-buffer',
      kind: 'sideBuffer',
    },
    {
      make: 'Furukawa',
      model: 'F22',
      file: 'takoz-furukawa-f22-buffer-guide',
      kind: 'bufferGuide',
    },
    { make: 'Furukawa', model: 'F22', file: 'takoz-furukawa-f22-top-buffer', kind: 'topBuffer' },
    {
      make: 'Furukawa',
      model: 'HB20G',
      file: 'takoz-furukawa-hb20g-side-buffer',
      kind: 'sideBuffer',
    },
    {
      make: 'Furukawa',
      model: 'HB30G',
      file: 'takoz-furukawa-hb30g-side-buffer',
      kind: 'sideBuffer',
    },
  ],
  akumulator: [
    {
      make: 'MTB',
      model: '210 II',
      file: 'pim-mtb-210-ii-accumulator-dowel',
      kind: 'accumulatorDowel',
    },
  ],
};

/** Tie rods with their nuts and washers (`saplama-takim-<kit>[-<nut shape>]`), one per nut shape. */
export const ROD_SETS: readonly SmallPart[] = [
  { make: 'Furukawa', model: 'F22', file: 'saplama-takim-furukawa-f22', kind: 'tieRodSet' },
  { make: 'Furukawa', model: 'HB20G', file: 'saplama-takim-furukawa-hb20g', kind: 'tieRodSet' },
  { make: 'Furukawa', model: 'HB30G', file: 'saplama-takim-furukawa-hb30g', kind: 'tieRodSet' },
  { make: 'Krupp', model: 'HM 1500', file: 'saplama-takim-krupp-hm-1500', kind: 'tieRodSet' },
  { make: 'Krupp', model: 'HM 560', file: 'saplama-takim-krupp-hm-560', kind: 'tieRodSet' },
  { make: 'Krupp', model: 'HM 720', file: 'saplama-takim-krupp-hm-720', kind: 'tieRodSet' },
  { make: 'Krupp', model: 'HM 960', file: 'saplama-takim-krupp-hm-960', kind: 'tieRodSet' },
  {
    make: 'Montabert',
    model: 'BRH 501',
    file: 'saplama-takim-montabert-brh-501',
    kind: 'tieRodSet',
  },
  { make: 'Montabert', model: 'BRV 32', file: 'saplama-takim-montabert-brv-32', kind: 'tieRodSet' },
  { make: 'MTB', model: '150', file: 'saplama-takim-mtb-150', kind: 'tieRodSet' },
  { make: 'Rammer', model: 'E64', file: 'saplama-takim-rammer-e64', kind: 'tieRodSet' },
  { make: 'Rammer', model: 'E66', file: 'saplama-takim-rammer-e66', kind: 'tieRodSet' },
  {
    make: 'Rammer',
    model: 'E66',
    file: 'saplama-takim-rammer-e66-newtype',
    kind: 'tieRodSet',
    variant: 'newType',
  },
  { make: 'Rammer', model: 'G80', file: 'saplama-takim-rammer-g80', kind: 'tieRodSet' },
  { make: 'Rammer', model: 'S25', file: 'saplama-takim-rammer-s25', kind: 'tieRodSet' },
  { make: 'Rammer', model: 'S84', file: 'saplama-takim-rammer-s84', kind: 'tieRodSet' },
  {
    make: 'Soosan',
    model: 'SB121 TS-P',
    file: 'saplama-takim-soosan-sb121-ts-p-newtype',
    kind: 'tieRodSet',
    variant: 'newType',
  },
  {
    make: 'Soosan',
    model: 'SB121 TS-P',
    file: 'saplama-takim-soosan-sb121-ts-p-trilobe',
    kind: 'tieRodSet',
    variant: 'triLobe',
  },
  {
    make: 'Soosan',
    model: 'SB121 TS-P',
    file: 'saplama-takim-soosan-sb121-ts-p-roundshape',
    kind: 'tieRodSet',
    variant: 'roundShape',
  },
];

/** Wear plates and buffers of one breaker in one picture (`asinma-set-<kit>`), hero only. */
export const WEAR_SETS: readonly SmallPart[] = [
  { make: 'Furukawa', model: 'F22', file: 'asinma-set-furukawa-f22', kind: 'wearPlateSet' },
  { make: 'Krupp', model: 'HM 1500', file: 'asinma-set-krupp-hm-1500', kind: 'wearPlateSet' },
  { make: 'Krupp', model: 'HM 560', file: 'asinma-set-krupp-hm-560', kind: 'wearPlateSet' },
  { make: 'Krupp', model: 'HM 720', file: 'asinma-set-krupp-hm-720', kind: 'wearPlateSet' },
  { make: 'Krupp', model: 'HM 960', file: 'asinma-set-krupp-hm-960', kind: 'wearPlateSet' },
  {
    make: 'Montabert',
    model: 'BRH 501',
    file: 'asinma-set-montabert-brh-501',
    kind: 'wearPlateSet',
  },
  { make: 'Montabert', model: 'BRV 32', file: 'asinma-set-montabert-brv-32', kind: 'wearPlateSet' },
  { make: 'MTB', model: '150', file: 'asinma-set-mtb-150', kind: 'wearPlateSet' },
  { make: 'MTB', model: '210', file: 'asinma-set-mtb-210', kind: 'wearPlateSet' },
  { make: 'MTB', model: '210 II', file: 'asinma-set-mtb-210-ii', kind: 'wearPlateSet' },
  { make: 'Rammer', model: 'E64', file: 'asinma-set-rammer-e64', kind: 'wearPlateSet' },
  { make: 'Rammer', model: 'G80', file: 'asinma-set-rammer-g80', kind: 'wearPlateSet' },
  { make: 'Rammer', model: 'S84', file: 'asinma-set-rammer-s84', kind: 'wearPlateSet' },
  {
    make: 'Soosan',
    model: 'SB121 TS-P',
    file: 'asinma-set-soosan-sb121-ts-p',
    kind: 'wearPlateSet',
  },
];

/** Bushing sets: the tool, upper and thrust bushings of one breaker (and its bushing pins) in one
 *  picture (`burc-takim-<make>-<model>[-<variant>]`), hero only. */
export const BUSHING_SETS: readonly SmallPart[] = [
  { make: 'Rammer', model: 'E64', file: 'burc-takim-rammer-e64', kind: 'bushingSet' },
  { make: 'Rammer', model: 'E66 N', file: 'burc-takim-rammer-e66-n', kind: 'bushingSet' },
  { make: 'Rammer', model: 'G80', file: 'burc-takim-rammer-g80', kind: 'bushingSet' },
  { make: 'Rammer', model: 'G88', file: 'burc-takim-rammer-g88', kind: 'bushingSet' },
  { make: 'Rammer', model: 'G90', file: 'burc-takim-rammer-g90', kind: 'bushingSet' },
  { make: 'Rammer', model: 'G100', file: 'burc-takim-rammer-g100', kind: 'bushingSet' },
  { make: 'Rammer', model: 'S21', file: 'burc-takim-rammer-s21', kind: 'bushingSet' },
  { make: 'Rammer', model: 'S23', file: 'burc-takim-rammer-s23', kind: 'bushingSet' },
  { make: 'Rammer', model: 'S25', file: 'burc-takim-rammer-s25', kind: 'bushingSet' },
  { make: 'Rammer', model: 'S26', file: 'burc-takim-rammer-s26', kind: 'bushingSet' },
  { make: 'Rammer', model: 'S27', file: 'burc-takim-rammer-s27', kind: 'bushingSet' },
  { make: 'Rammer', model: 'S29', file: 'burc-takim-rammer-s29', kind: 'bushingSet' },
  { make: 'Rammer', model: 'S54', file: 'burc-takim-rammer-s54', kind: 'bushingSet' },
  { make: 'Rammer', model: 'S55', file: 'burc-takim-rammer-s55', kind: 'bushingSet' },
  { make: 'Rammer', model: 'S56', file: 'burc-takim-rammer-s56', kind: 'bushingSet' },
  { make: 'Rammer', model: 'S82', file: 'burc-takim-rammer-s82', kind: 'bushingSet' },
  { make: 'Rammer', model: 'S83', file: 'burc-takim-rammer-s83', kind: 'bushingSet' },
  { make: 'Rammer', model: 'S84', file: 'burc-takim-rammer-s84', kind: 'bushingSet' },
  { make: 'MTB', model: '15', file: 'burc-takim-mtb-15', kind: 'bushingSet' },
  { make: 'MTB', model: '30', file: 'burc-takim-mtb-30', kind: 'bushingSet' },
  { make: 'MTB', model: '40', file: 'burc-takim-mtb-40', kind: 'bushingSet' },
  { make: 'MTB', model: '45', file: 'burc-takim-mtb-45', kind: 'bushingSet' },
  { make: 'MTB', model: '65', file: 'burc-takim-mtb-65', kind: 'bushingSet' },
  { make: 'MTB', model: '85', file: 'burc-takim-mtb-85', kind: 'bushingSet' },
  { make: 'MTB', model: '120', file: 'burc-takim-mtb-120', kind: 'bushingSet' },
  { make: 'MTB', model: '125', file: 'burc-takim-mtb-125', kind: 'bushingSet' },
  { make: 'MTB', model: '150', file: 'burc-takim-mtb-150', kind: 'bushingSet' },
  { make: 'MTB', model: '170', file: 'burc-takim-mtb-170', kind: 'bushingSet' },
  { make: 'MTB', model: '210', file: 'burc-takim-mtb-210', kind: 'bushingSet' },
  { make: 'MTB', model: '220', file: 'burc-takim-mtb-220', kind: 'bushingSet' },
  { make: 'MTB', model: '360', file: 'burc-takim-mtb-360', kind: 'bushingSet' },
  { make: 'MTB', model: '500', file: 'burc-takim-mtb-500', kind: 'bushingSet' },
  {
    make: 'Krupp',
    model: 'HM 60 / 61 / 62',
    file: 'burc-takim-krupp-hm-60-61-62',
    kind: 'bushingSet',
  },
  { make: 'Krupp', model: 'HM 135', file: 'burc-takim-krupp-hm-135', kind: 'bushingSet' },
  { make: 'Krupp', model: 'HM 185', file: 'burc-takim-krupp-hm-185', kind: 'bushingSet' },
  { make: 'Krupp', model: 'HM 200', file: 'burc-takim-krupp-hm-200', kind: 'bushingSet' },
  {
    make: 'Krupp',
    model: 'HM 300 / 301 / 305',
    file: 'burc-takim-krupp-hm-300-301-305',
    kind: 'bushingSet',
  },
  { make: 'Krupp', model: 'HM 350', file: 'burc-takim-krupp-hm-350', kind: 'bushingSet' },
  {
    make: 'Krupp',
    model: 'HM 550 / 551 / 555',
    file: 'burc-takim-krupp-hm-550-551-555',
    kind: 'bushingSet',
  },
  { make: 'Krupp', model: 'HM 560', file: 'burc-takim-krupp-hm-560', kind: 'bushingSet' },
  { make: 'Krupp', model: 'HM 580', file: 'burc-takim-krupp-hm-580', kind: 'bushingSet' },
  { make: 'Krupp', model: 'HM 600', file: 'burc-takim-krupp-hm-600', kind: 'bushingSet' },
  {
    make: 'Krupp',
    model: 'HM 700 / 701 / 702',
    file: 'burc-takim-krupp-hm-700-701-702',
    kind: 'bushingSet',
  },
  {
    make: 'Krupp',
    model: 'HM 720 / 721 / 722',
    file: 'burc-takim-krupp-hm-720-721-722',
    kind: 'bushingSet',
  },
  { make: 'Krupp', model: 'HM 780', file: 'burc-takim-krupp-hm-780', kind: 'bushingSet' },
  { make: 'Krupp', model: 'HM 800', file: 'burc-takim-krupp-hm-800', kind: 'bushingSet' },
  {
    make: 'Krupp',
    model: 'HM 900 / 901 / 902',
    file: 'burc-takim-krupp-hm-900-901-902',
    kind: 'bushingSet',
  },
  {
    make: 'Krupp',
    model: 'HM 950 / 951 / 952',
    file: 'burc-takim-krupp-hm-950-951-952',
    kind: 'bushingSet',
  },
  {
    make: 'Krupp',
    model: 'HM 960 / 961 / 962',
    file: 'burc-takim-krupp-hm-960-961-962',
    kind: 'bushingSet',
  },
  { make: 'Krupp', model: 'HM 1000', file: 'burc-takim-krupp-hm-1000', kind: 'bushingSet' },
  { make: 'Krupp', model: 'HM 1201', file: 'burc-takim-krupp-hm-1201', kind: 'bushingSet' },
  { make: 'Krupp', model: 'HM 1500', file: 'burc-takim-krupp-hm-1500', kind: 'bushingSet' },
  { make: 'Krupp', model: 'HM 2000', file: 'burc-takim-krupp-hm-2000', kind: 'bushingSet' },
  {
    make: 'Krupp',
    model: 'HM 2000',
    file: 'burc-takim-krupp-hm-2000-newtype',
    kind: 'bushingSet',
    variant: 'newType',
  },
  {
    make: 'Krupp',
    model: 'HM 2000 Marathon',
    file: 'burc-takim-krupp-hm-2000-marathon',
    kind: 'bushingSet',
  },
  {
    make: 'Krupp',
    model: 'HM 2300 Marathon',
    file: 'burc-takim-krupp-hm-2300-marathon',
    kind: 'bushingSet',
  },
  {
    make: 'Krupp',
    model: 'HM 2500 Marathon',
    file: 'burc-takim-krupp-hm-2500-marathon',
    kind: 'bushingSet',
  },
  {
    make: 'Krupp',
    model: 'HM 2600 Marathon',
    file: 'burc-takim-krupp-hm-2600-marathon',
    kind: 'bushingSet',
  },
  {
    make: 'Atlas Copco',
    model: 'HB 2200',
    file: 'burc-takim-atlas-copco-hb-2200',
    kind: 'bushingSet',
  },
  {
    make: 'Atlas Copco',
    model: 'HB 2500',
    file: 'burc-takim-atlas-copco-hb-2500',
    kind: 'bushingSet',
  },
  {
    make: 'Atlas Copco',
    model: 'HB 3000',
    file: 'burc-takim-atlas-copco-hb-3000',
    kind: 'bushingSet',
  },
  {
    make: 'Atlas Copco',
    model: 'MB 1000 (Krupp HM 680)',
    file: 'burc-takim-atlas-copco-mb-1000-krupp-hm-680',
    kind: 'bushingSet',
  },
  {
    make: 'Atlas Copco',
    model: 'MB 1200',
    file: 'burc-takim-atlas-copco-mb-1200',
    kind: 'bushingSet',
  },
  {
    make: 'Atlas Copco',
    model: 'MB 1700',
    file: 'burc-takim-atlas-copco-mb-1700',
    kind: 'bushingSet',
  },
  {
    make: 'Atlas Copco',
    model: 'HBC 4000',
    file: 'burc-takim-atlas-copco-hbc-4000',
    kind: 'bushingSet',
  },
  {
    make: 'Atlas Copco',
    model: 'TEX 700 / 900',
    file: 'burc-takim-atlas-copco-tex-700-900',
    kind: 'bushingSet',
  },
  {
    make: 'Atlas Copco',
    model: 'TEX 1400',
    file: 'burc-takim-atlas-copco-tex-1400',
    kind: 'bushingSet',
  },
  { make: 'Soosan', model: 'SB10 TS-P', file: 'burc-takim-soosan-sb10-ts-p', kind: 'bushingSet' },
  { make: 'Soosan', model: 'SB20 TS-P', file: 'burc-takim-soosan-sb20-ts-p', kind: 'bushingSet' },
  { make: 'Soosan', model: 'SB30 TS-P', file: 'burc-takim-soosan-sb30-ts-p', kind: 'bushingSet' },
  { make: 'Soosan', model: 'SB40', file: 'burc-takim-soosan-sb40', kind: 'bushingSet' },
  { make: 'Soosan', model: 'SB43 TS-P', file: 'burc-takim-soosan-sb43-ts-p', kind: 'bushingSet' },
  { make: 'Soosan', model: 'SB45 TS-P', file: 'burc-takim-soosan-sb45-ts-p', kind: 'bushingSet' },
  { make: 'Soosan', model: 'SB50 TS-P', file: 'burc-takim-soosan-sb50-ts-p', kind: 'bushingSet' },
  { make: 'Soosan', model: 'SB60', file: 'burc-takim-soosan-sb60', kind: 'bushingSet' },
  { make: 'Soosan', model: 'SB60 TS-P', file: 'burc-takim-soosan-sb60-ts-p', kind: 'bushingSet' },
  { make: 'Soosan', model: 'SB70 TS-P', file: 'burc-takim-soosan-sb70-ts-p', kind: 'bushingSet' },
  { make: 'Soosan', model: 'SB80', file: 'burc-takim-soosan-sb80', kind: 'bushingSet' },
  { make: 'Soosan', model: 'SB81 TS-P', file: 'burc-takim-soosan-sb81-ts-p', kind: 'bushingSet' },
  { make: 'Soosan', model: 'SB100 TS-P', file: 'burc-takim-soosan-sb100-ts-p', kind: 'bushingSet' },
  { make: 'Soosan', model: 'SB120', file: 'burc-takim-soosan-sb120', kind: 'bushingSet' },
  { make: 'Soosan', model: 'SB121 TS-P', file: 'burc-takim-soosan-sb121-ts-p', kind: 'bushingSet' },
  { make: 'Soosan', model: 'SB130 TS-P', file: 'burc-takim-soosan-sb130-ts-p', kind: 'bushingSet' },
  { make: 'Soosan', model: 'SB150', file: 'burc-takim-soosan-sb150', kind: 'bushingSet' },
  { make: 'Soosan', model: 'SB151 TS-P', file: 'burc-takim-soosan-sb151-ts-p', kind: 'bushingSet' },
  { make: 'Soosan', model: 'ST180', file: 'burc-takim-soosan-st180', kind: 'bushingSet' },
  { make: 'Montabert', model: 'BRH 501', file: 'burc-takim-montabert-brh-501', kind: 'bushingSet' },
  { make: 'Montabert', model: 'BRH 570', file: 'burc-takim-montabert-brh-570', kind: 'bushingSet' },
  { make: 'Montabert', model: 'BRH 620', file: 'burc-takim-montabert-brh-620', kind: 'bushingSet' },
  { make: 'Montabert', model: 'BRH 625', file: 'burc-takim-montabert-brh-625', kind: 'bushingSet' },
  { make: 'Montabert', model: 'BRH 750', file: 'burc-takim-montabert-brh-750', kind: 'bushingSet' },
  {
    make: 'Montabert',
    model: 'BRH 1100',
    file: 'burc-takim-montabert-brh-1100',
    kind: 'bushingSet',
  },
  { make: 'Montabert', model: 'BRM 900', file: 'burc-takim-montabert-brm-900', kind: 'bushingSet' },
  {
    make: 'Montabert',
    model: 'BRM 1200 V',
    file: 'burc-takim-montabert-brm-1200-v',
    kind: 'bushingSet',
  },
  {
    make: 'Montabert',
    model: 'BRM 1600 V',
    file: 'burc-takim-montabert-brm-1600-v',
    kind: 'bushingSet',
  },
  { make: 'Montabert', model: 'BRP 50', file: 'burc-takim-montabert-brp-50', kind: 'bushingSet' },
  { make: 'Montabert', model: 'BRP 95', file: 'burc-takim-montabert-brp-95', kind: 'bushingSet' },
  { make: 'Montabert', model: 'BRP 140', file: 'burc-takim-montabert-brp-140', kind: 'bushingSet' },
  { make: 'Montabert', model: 'BRP 150', file: 'burc-takim-montabert-brp-150', kind: 'bushingSet' },
  { make: 'Montabert', model: 'BRV 32', file: 'burc-takim-montabert-brv-32', kind: 'bushingSet' },
  { make: 'Montabert', model: 'BRV 43', file: 'burc-takim-montabert-brv-43', kind: 'bushingSet' },
  {
    make: 'Montabert',
    model: 'BRV 45 V',
    file: 'burc-takim-montabert-brv-45-v',
    kind: 'bushingSet',
  },
  {
    make: 'Montabert',
    model: 'BRV 45 V',
    file: 'burc-takim-montabert-brv-45-v-newtype',
    kind: 'bushingSet',
    variant: 'newType',
  },
  {
    make: 'Montabert',
    model: 'BRV 65 V',
    file: 'burc-takim-montabert-brv-65-v',
    kind: 'bushingSet',
  },
  { make: 'Montabert', model: 'M 600', file: 'burc-takim-montabert-m-600', kind: 'bushingSet' },
  { make: 'Montabert', model: 'M 700', file: 'burc-takim-montabert-m-700', kind: 'bushingSet' },
  { make: 'Furukawa', model: 'F6', file: 'burc-takim-furukawa-f6', kind: 'bushingSet' },
  { make: 'Furukawa', model: 'F19', file: 'burc-takim-furukawa-f19', kind: 'bushingSet' },
  { make: 'Furukawa', model: 'F22', file: 'burc-takim-furukawa-f22', kind: 'bushingSet' },
  { make: 'Furukawa', model: 'F27', file: 'burc-takim-furukawa-f27', kind: 'bushingSet' },
  { make: 'Furukawa', model: 'F35', file: 'burc-takim-furukawa-f35', kind: 'bushingSet' },
  { make: 'Furukawa', model: 'F100', file: 'burc-takim-furukawa-f100', kind: 'bushingSet' },
  { make: 'Furukawa', model: 'HB15G', file: 'burc-takim-furukawa-hb15g', kind: 'bushingSet' },
  { make: 'Furukawa', model: 'HB20G', file: 'burc-takim-furukawa-hb20g', kind: 'bushingSet' },
  { make: 'Furukawa', model: 'HB30G', file: 'burc-takim-furukawa-hb30g', kind: 'bushingSet' },
  { make: 'Furukawa', model: 'HB40G', file: 'burc-takim-furukawa-hb40g', kind: 'bushingSet' },
  { make: 'Furukawa', model: 'HB1000', file: 'burc-takim-furukawa-hb1000', kind: 'bushingSet' },
  { make: 'Furukawa', model: 'HB1200', file: 'burc-takim-furukawa-hb1200', kind: 'bushingSet' },
  { make: 'Furukawa', model: 'HB2000', file: 'burc-takim-furukawa-hb2000', kind: 'bushingSet' },
  { make: 'NPK', model: 'E-210', file: 'burc-takim-npk-e-210', kind: 'bushingSet' },
  { make: 'NPK', model: 'E-213A', file: 'burc-takim-npk-e-213a', kind: 'bushingSet' },
  { make: 'NPK', model: 'E-216', file: 'burc-takim-npk-e-216', kind: 'bushingSet' },
  { make: 'NPK', model: 'E-220', file: 'burc-takim-npk-e-220', kind: 'bushingSet' },
  { make: 'NPK', model: 'GH-15', file: 'burc-takim-npk-gh-15', kind: 'bushingSet' },
  { make: 'NPK', model: 'H-2XA', file: 'burc-takim-npk-h-2xa', kind: 'bushingSet' },
  { make: 'NPK', model: 'H-3XA', file: 'burc-takim-npk-h-3xa', kind: 'bushingSet' },
  { make: 'NPK', model: 'H-7X', file: 'burc-takim-npk-h-7x', kind: 'bushingSet' },
  { make: 'NPK', model: 'H-08X', file: 'burc-takim-npk-h-08x', kind: 'bushingSet' },
  { make: 'NPK', model: 'H-8XA', file: 'burc-takim-npk-h-8xa', kind: 'bushingSet' },
  { make: 'NPK', model: 'H-12X', file: 'burc-takim-npk-h-12x', kind: 'bushingSet' },
  { make: 'NPK', model: 'H-16X', file: 'burc-takim-npk-h-16x', kind: 'bushingSet' },
  { make: 'NPK', model: 'H-20XE', file: 'burc-takim-npk-h-20xe', kind: 'bushingSet' },
  { make: 'Indeco', model: 'HB 8', file: 'burc-takim-indeco-hb-8', kind: 'bushingSet' },
  { make: 'Indeco', model: 'HB 19', file: 'burc-takim-indeco-hb-19', kind: 'bushingSet' },
  { make: 'Indeco', model: 'HB 27', file: 'burc-takim-indeco-hb-27', kind: 'bushingSet' },
  { make: 'Indeco', model: 'MES 621', file: 'burc-takim-indeco-mes-621', kind: 'bushingSet' },
  { make: 'Indeco', model: 'MES 1200', file: 'burc-takim-indeco-mes-1200', kind: 'bushingSet' },
  { make: 'Indeco', model: 'MES 1750', file: 'burc-takim-indeco-mes-1750', kind: 'bushingSet' },
  { make: 'Indeco', model: 'MES 2000', file: 'burc-takim-indeco-mes-2000', kind: 'bushingSet' },
  { make: 'Indeco', model: 'MES 2500', file: 'burc-takim-indeco-mes-2500', kind: 'bushingSet' },
  { make: 'Indeco', model: 'MES 3000', file: 'burc-takim-indeco-mes-3000', kind: 'bushingSet' },
  { make: 'Indeco', model: 'MES 3500', file: 'burc-takim-indeco-mes-3500', kind: 'bushingSet' },
  { make: 'Indeco', model: 'MES 4000', file: 'burc-takim-indeco-mes-4000', kind: 'bushingSet' },
  { make: 'Daemo', model: 'S500', file: 'burc-takim-daemo-s500', kind: 'bushingSet' },
  { make: 'Daemo', model: 'S700', file: 'burc-takim-daemo-s700', kind: 'bushingSet' },
  { make: 'Daemo', model: 'S1800', file: 'burc-takim-daemo-s1800', kind: 'bushingSet' },
  { make: 'Daemo', model: 'S2000', file: 'burc-takim-daemo-s2000', kind: 'bushingSet' },
  { make: 'Daemo', model: 'S2200', file: 'burc-takim-daemo-s2200', kind: 'bushingSet' },
  { make: 'Daemo', model: 'S2200 II', file: 'burc-takim-daemo-s2200-ii', kind: 'bushingSet' },
  { make: 'Hanwoo', model: 'RHB 305V', file: 'burc-takim-hanwoo-rhb-305v', kind: 'bushingSet' },
  { make: 'Hanwoo', model: 'RHB 313', file: 'burc-takim-hanwoo-rhb-313', kind: 'bushingSet' },
  { make: 'Hanwoo', model: 'RHB 320', file: 'burc-takim-hanwoo-rhb-320', kind: 'bushingSet' },
  { make: 'Hanwoo', model: 'RHB 322', file: 'burc-takim-hanwoo-rhb-322', kind: 'bushingSet' },
  { make: 'Hanwoo', model: 'RHB 325', file: 'burc-takim-hanwoo-rhb-325', kind: 'bushingSet' },
  { make: 'Hanwoo', model: 'RHB 330', file: 'burc-takim-hanwoo-rhb-330', kind: 'bushingSet' },
  { make: 'Hanwoo', model: 'RHB 332', file: 'burc-takim-hanwoo-rhb-332', kind: 'bushingSet' },
  { make: 'Hanwoo', model: 'RHB 340', file: 'burc-takim-hanwoo-rhb-340', kind: 'bushingSet' },
  { make: 'DNB', model: 'D60', file: 'burc-takim-dnb-d60', kind: 'bushingSet' },
  { make: 'DNB', model: 'D70 / D90', file: 'burc-takim-dnb-d70-d90', kind: 'bushingSet' },
  { make: 'DNB', model: 'D110', file: 'burc-takim-dnb-d110', kind: 'bushingSet' },
  { make: 'DNB', model: 'D110 IIS', file: 'burc-takim-dnb-d110-iis', kind: 'bushingSet' },
  { make: 'DNB', model: 'D130 IIS', file: 'burc-takim-dnb-d130-iis', kind: 'bushingSet' },
  { make: 'DNB', model: 'D160 IIS', file: 'burc-takim-dnb-d160-iis', kind: 'bushingSet' },
  { make: 'Cat', model: '115', file: 'burc-takim-cat-115', kind: 'bushingSet' },
  { make: 'Cat', model: '130', file: 'burc-takim-cat-130', kind: 'bushingSet' },
  { make: 'Cat', model: '140', file: 'burc-takim-cat-140', kind: 'bushingSet' },
  { make: 'Cat', model: '160', file: 'burc-takim-cat-160', kind: 'bushingSet' },
  { make: 'MSB', model: '250', file: 'burc-takim-msb-250', kind: 'bushingSet' },
  { make: 'MSB', model: '450', file: 'burc-takim-msb-450', kind: 'bushingSet' },
  { make: 'MSB', model: '500', file: 'burc-takim-msb-500', kind: 'bushingSet' },
  { make: 'MSB', model: '600', file: 'burc-takim-msb-600', kind: 'bushingSet' },
  { make: 'MSB', model: '700', file: 'burc-takim-msb-700', kind: 'bushingSet' },
  { make: 'MSB', model: '750', file: 'burc-takim-msb-750', kind: 'bushingSet' },
  { make: 'MSB', model: 'MS 810', file: 'burc-takim-msb-ms-810', kind: 'bushingSet' },
  { make: 'MSB', model: 'SAGA 6000', file: 'burc-takim-msb-saga-6000', kind: 'bushingSet' },
  { make: 'Toku', model: 'TNB-1E', file: 'burc-takim-toku-tnb-1e', kind: 'bushingSet' },
  { make: 'Toku', model: 'TNB-6E', file: 'burc-takim-toku-tnb-6e', kind: 'bushingSet' },
  { make: 'Toku', model: 'TNB-7E', file: 'burc-takim-toku-tnb-7e', kind: 'bushingSet' },
  { make: 'Toku', model: 'TNB-14E', file: 'burc-takim-toku-tnb-14e', kind: 'bushingSet' },
  { make: 'Toku', model: 'TNB-16E', file: 'burc-takim-toku-tnb-16e', kind: 'bushingSet' },
  { make: 'Toku', model: 'TNB-22E', file: 'burc-takim-toku-tnb-22e', kind: 'bushingSet' },
  { make: 'Kwanglim', model: 'SG-800S', file: 'burc-takim-kwanglim-sg-800s', kind: 'bushingSet' },
  { make: 'Kwanglim', model: 'SG-2100', file: 'burc-takim-kwanglim-sg-2100', kind: 'bushingSet' },
  { make: 'Kwanglim', model: 'SG-2800', file: 'burc-takim-kwanglim-sg-2800', kind: 'bushingSet' },
  { make: 'Kanglim', model: 'KTB 400', file: 'burc-takim-kanglim-ktb-400', kind: 'bushingSet' },
  { make: 'Kanglim', model: 'KTB 1800', file: 'burc-takim-kanglim-ktb-1800', kind: 'bushingSet' },
  { make: 'D&A', model: '130V', file: 'burc-takim-d-a-130v', kind: 'bushingSet' },
  { make: 'D&A', model: '200V', file: 'burc-takim-d-a-200v', kind: 'bushingSet' },
  { make: 'D&A', model: '300V', file: 'burc-takim-d-a-300v', kind: 'bushingSet' },
  { make: 'D&A', model: '1300', file: 'burc-takim-d-a-1300', kind: 'bushingSet' },
  { make: 'D&A', model: '1800', file: 'burc-takim-d-a-1800', kind: 'bushingSet' },
  { make: 'Topa', model: '900', file: 'burc-takim-topa-900', kind: 'bushingSet' },
  { make: 'Topa', model: '900N', file: 'burc-takim-topa-900n', kind: 'bushingSet' },
  { make: 'Topa', model: '1400', file: 'burc-takim-topa-1400', kind: 'bushingSet' },
  { make: 'Mega', model: '130', file: 'burc-takim-mega-130', kind: 'bushingSet' },
  { make: 'Mega', model: '280', file: 'burc-takim-mega-280', kind: 'bushingSet' },
  { make: 'Kent', model: 'K 70', file: 'burc-takim-kent-k-70', kind: 'bushingSet' },
  { make: 'Kent', model: 'K 90', file: 'burc-takim-kent-k-90', kind: 'bushingSet' },
  { make: 'Okada', model: 'OKB 304B', file: 'burc-takim-okada-okb-304b', kind: 'bushingSet' },
  { make: 'Okada', model: 'OKB 308', file: 'burc-takim-okada-okb-308', kind: 'bushingSet' },
  { make: 'Okada', model: 'OKB 310', file: 'burc-takim-okada-okb-310', kind: 'bushingSet' },
  { make: 'Okada', model: 'OKB 312', file: 'burc-takim-okada-okb-312', kind: 'bushingSet' },
  { make: 'Okada', model: 'OKB 316', file: 'burc-takim-okada-okb-316', kind: 'bushingSet' },
  { make: 'Okada', model: 'TOP 200', file: 'burc-takim-okada-top-200', kind: 'bushingSet' },
  { make: 'Okada', model: 'TOP 300', file: 'burc-takim-okada-top-300', kind: 'bushingSet' },
  { make: 'Toyo', model: 'THBB 301', file: 'burc-takim-toyo-thbb-301', kind: 'bushingSet' },
  { make: 'Toyo', model: 'THBB 401', file: 'burc-takim-toyo-thbb-401', kind: 'bushingSet' },
  { make: 'Toyo', model: 'THBB 801', file: 'burc-takim-toyo-thbb-801', kind: 'bushingSet' },
  { make: 'Toyo', model: 'THBB 1101', file: 'burc-takim-toyo-thbb-1101', kind: 'bushingSet' },
  { make: 'Toyo', model: 'THBB 1400', file: 'burc-takim-toyo-thbb-1400', kind: 'bushingSet' },
  { make: 'Toyo', model: 'THBB 1401', file: 'burc-takim-toyo-thbb-1401', kind: 'bushingSet' },
  { make: 'Toyo', model: 'THBB 1600', file: 'burc-takim-toyo-thbb-1600', kind: 'bushingSet' },
  { make: 'Toyo', model: 'THBB 2000', file: 'burc-takim-toyo-thbb-2000', kind: 'bushingSet' },
  { make: 'Toyo', model: 'THBB 3000', file: 'burc-takim-toyo-thbb-3000', kind: 'bushingSet' },
  { make: 'Jisung', model: 'JSB-40', file: 'burc-takim-jisung-jsb-40', kind: 'bushingSet' },
  { make: 'Lifton', model: 'LH 360', file: 'burc-takim-lifton-lh-360', kind: 'bushingSet' },
  { make: 'Tabe', model: 'AGB 16', file: 'burc-takim-tabe-agb-16', kind: 'bushingSet' },
  { make: 'Arrowhead', model: 'HB-6T', file: 'burc-takim-arrowhead-hb-6t', kind: 'bushingSet' },
  { make: 'Euroram', model: 'HB-6T', file: 'burc-takim-euroram-hb-6t', kind: 'bushingSet' },
  { make: 'Rammer', model: 'E68', file: 'burc-takim-rammer-e68', kind: 'bushingSet' },
];
