/** Generated from the owner's drawings (nuts, washers, pins, plugs, buffers, wear plates): one render each,
 *  `/photos/parca/<file>-{vitrin,yan,on,arka}-01`. Names come from the drawing titles (`kind`), never part numbers. */
import type { PartRender } from './photos';

export interface SmallPart {
  make: string;
  model: string;
  file: string;
  kind: NonNullable<PartRender['kind']>;
  variant?: PartRender['variant'];
}

export const SMALL_PARTS: Record<
  'saplama' | 'kama' | 'burc' | 'asinma-plakasi' | 'akumulator',
  readonly SmallPart[]
> = {
  saplama: [
    { make: 'Rammer', model: 'E64', file: 'somun-rammer-e64-tie-rod-nut', kind: 'tieRodNut' },
    { make: 'Rammer', model: 'E66', file: 'somun-rammer-e66-tie-rod-nut', kind: 'tieRodNut' },
    {
      make: 'Rammer',
      model: 'E66',
      file: 'somun-rammer-e66-tie-rod-nut-new-type',
      kind: 'tieRodNut',
      variant: 'newType',
    },
    { make: 'Rammer', model: 'G80', file: 'somun-rammer-g80-tie-rod-nut', kind: 'tieRodNut' },
    { make: 'Rammer', model: 'S25', file: 'somun-rammer-s25-tie-rod-nut', kind: 'tieRodNut' },
    { make: 'Rammer', model: 'S25', file: 'pul-rammer-s25-tie-rod-washer', kind: 'tieRodWasher' },
    { make: 'Rammer', model: 'S84', file: 'somun-rammer-s84-tie-rod-nut', kind: 'tieRodNut' },
    { make: 'MTB', model: '150', file: 'somun-mtb-150-tie-rod-nut', kind: 'tieRodNut' },
    { make: 'MTB', model: '210 II', file: 'somun-mtb-210-ii-tie-rod-nut', kind: 'tieRodNut' },
    { make: 'Krupp', model: 'HM 1500', file: 'pim-krupp-hm-1500-body-dowel', kind: 'bodyDowel' },
    { make: 'Krupp', model: 'HM 1500', file: 'somun-krupp-hm-1500-tie-rod-nut', kind: 'tieRodNut' },
    {
      make: 'Krupp',
      model: 'HM 1500',
      file: 'pul-krupp-hm-1500-tie-rod-washer',
      kind: 'tieRodWasher',
    },
    { make: 'Krupp', model: 'HM 560', file: 'somun-krupp-hm-560-tie-rod-nut', kind: 'tieRodNut' },
    {
      make: 'Krupp',
      model: 'HM 560',
      file: 'pul-krupp-hm-560-tie-rod-washer',
      kind: 'tieRodWasher',
    },
    { make: 'Krupp', model: 'HM 720', file: 'pul-krupp-hm-720-tie-rod-bush', kind: 'tieRodBush' },
    {
      make: 'Krupp',
      model: 'HM 720',
      file: 'somun-krupp-hm-720-tie-rod-lower-nut',
      kind: 'tieRodLowerNut',
    },
    {
      make: 'Krupp',
      model: 'HM 720',
      file: 'somun-krupp-hm-720-tie-rod-upper-nut',
      kind: 'tieRodUpperNut',
    },
    {
      make: 'Krupp',
      model: 'HM 720',
      file: 'pul-krupp-hm-720-tie-rod-washer',
      kind: 'tieRodWasher',
    },
    { make: 'Krupp', model: 'HM 960', file: 'pul-krupp-hm-960-tie-rod-bush', kind: 'tieRodBush' },
    {
      make: 'Krupp',
      model: 'HM 960',
      file: 'somun-krupp-hm-960-tie-rod-lower-nut',
      kind: 'tieRodLowerNut',
    },
    {
      make: 'Krupp',
      model: 'HM 960',
      file: 'somun-krupp-hm-960-tie-rod-upper-nut',
      kind: 'tieRodUpperNut',
    },
    {
      make: 'Krupp',
      model: 'HM 960',
      file: 'pul-krupp-hm-960-tie-rod-washer',
      kind: 'tieRodWasher',
    },
    {
      make: 'Krupp',
      model: 'HM 960',
      file: 'pul-krupp-hm-960-tie-rod-washer-new-type',
      kind: 'tieRodWasher',
      variant: 'newType',
    },
    {
      make: 'Soosan',
      model: 'SB121 TS-P',
      file: 'somun-soosan-sb121-ts-p-tie-rod-lower-nut-new-type',
      kind: 'tieRodLowerNut',
      variant: 'newType',
    },
    {
      make: 'Soosan',
      model: 'SB121 TS-P',
      file: 'somun-soosan-sb121-ts-p-tie-rod-lower-nut-round-nut',
      kind: 'tieRodLowerNut',
      variant: 'roundShape',
    },
    {
      make: 'Soosan',
      model: 'SB121 TS-P',
      file: 'somun-soosan-sb121-ts-p-tie-rod-lower-nut-tri-nut',
      kind: 'tieRodLowerNut',
      variant: 'triLobe',
    },
    {
      make: 'Soosan',
      model: 'SB121 TS-P',
      file: 'somun-soosan-sb121-ts-p-tie-rod-upper-nut',
      kind: 'tieRodUpperNut',
    },
    {
      make: 'Soosan',
      model: 'SB121 TS-P',
      file: 'pul-soosan-sb121-ts-p-tie-rod-washer',
      kind: 'tieRodWasher',
    },
    {
      make: 'Montabert',
      model: 'BRH 501',
      file: 'somun-montabert-brh-501-tie-rod-nut',
      kind: 'tieRodNut',
    },
    {
      make: 'Montabert',
      model: 'BRV 32',
      file: 'somun-montabert-brv-32-tie-rod-nut',
      kind: 'tieRodNut',
    },
    {
      make: 'Furukawa',
      model: 'F22',
      file: 'somun-furukawa-f22-tie-rod-lower-nut',
      kind: 'tieRodLowerNut',
    },
    {
      make: 'Furukawa',
      model: 'F22',
      file: 'somun-furukawa-f22-tie-rod-upper-nut',
      kind: 'tieRodUpperNut',
    },
    {
      make: 'Furukawa',
      model: 'HB20G',
      file: 'pul-furukawa-hb20g-side-bolt-washer',
      kind: 'sideBoltWasher',
    },
    {
      make: 'Furukawa',
      model: 'HB20G',
      file: 'pul-furukawa-hb20g-side-bolt-washer-new-type',
      kind: 'sideBoltWasher',
      variant: 'newType',
    },
    {
      make: 'Furukawa',
      model: 'HB20G',
      file: 'somun-furukawa-hb20g-tie-rod-lower-nut',
      kind: 'tieRodLowerNut',
    },
    {
      make: 'Furukawa',
      model: 'HB20G',
      file: 'somun-furukawa-hb20g-tie-rod-lower-nut-old-type',
      kind: 'tieRodLowerNut',
      variant: 'oldType',
    },
    {
      make: 'Furukawa',
      model: 'HB20G',
      file: 'somun-furukawa-hb20g-tie-rod-upper-nut',
      kind: 'tieRodUpperNut',
    },
    {
      make: 'Furukawa',
      model: 'HB20G',
      file: 'somun-furukawa-hb20g-tie-rod-upper-nut-old-type',
      kind: 'tieRodUpperNut',
      variant: 'oldType',
    },
    {
      make: 'Furukawa',
      model: 'HB20G',
      file: 'pul-furukawa-hb20g-tie-rod-washer',
      kind: 'tieRodWasher',
    },
    {
      make: 'Furukawa',
      model: 'HB30G',
      file: 'somun-furukawa-hb30g-tie-rod-lower-nut',
      kind: 'tieRodLowerNut',
    },
    {
      make: 'Furukawa',
      model: 'HB30G',
      file: 'somun-furukawa-hb30g-tie-rod-lower-nut-old-type',
      kind: 'tieRodLowerNut',
      variant: 'oldType',
    },
    {
      make: 'Furukawa',
      model: 'HB30G',
      file: 'somun-furukawa-hb30g-tie-rod-upper-nut',
      kind: 'tieRodUpperNut',
    },
    {
      make: 'Furukawa',
      model: 'HB30G',
      file: 'somun-furukawa-hb30g-tie-rod-upper-nut-old-type',
      kind: 'tieRodUpperNut',
      variant: 'oldType',
    },
    {
      make: 'Furukawa',
      model: 'HB30G',
      file: 'pul-furukawa-hb30g-tie-rod-washer',
      kind: 'tieRodWasher',
    },
    {
      make: 'Furukawa',
      model: 'HB30G',
      file: 'pul-furukawa-hb30g-tie-rod-washer-old-type',
      kind: 'tieRodWasher',
      variant: 'oldType',
    },
  ],
  kama: [
    {
      make: 'Rammer',
      model: 'G80',
      file: 'pim-rammer-g80-key-pin-retainer',
      kind: 'keyPinRetainer',
    },
    { make: 'Rammer', model: 'G80', file: 'pul-rammer-g80-key-pin-washer', kind: 'keyPinWasher' },
    {
      make: 'Rammer',
      model: 'S84',
      file: 'pim-rammer-s84-retainer-lock-pin',
      kind: 'retainerLockPin',
    },
    { make: 'MTB', model: '210', file: 'pim-mtb-210-key-pin-holder', kind: 'keyPinHolder' },
    { make: 'MTB', model: '210', file: 'pim-mtb-210-retainer-lock-pin', kind: 'retainerLockPin' },
    { make: 'MTB', model: '210 II', file: 'tapa-mtb-210-ii-key-pin-plug', kind: 'keyPinPlug' },
    { make: 'MTB', model: '210 II', file: 'pim-mtb-210-ii-retainer-pin', kind: 'retainerPin' },
    {
      make: 'Krupp',
      model: 'HM 720',
      file: 'pim-krupp-hm-720-key-pin-rubber',
      kind: 'keyPinRubber',
    },
    {
      make: 'Krupp',
      model: 'HM 720',
      file: 'pim-krupp-hm-720-retainer-pin',
      kind: 'retainerPin',
      variant: 'oldType',
    },
    {
      make: 'Montabert',
      model: 'BRV 32',
      file: 'pim-montabert-brv-32-lower-retainer-pin',
      kind: 'lowerRetainerPin',
    },
    {
      make: 'Montabert',
      model: 'BRV 32',
      file: 'pim-montabert-brv-32-retainer-pin',
      kind: 'retainerPin',
    },
    {
      make: 'Montabert',
      model: 'BRV 32',
      file: 'pim-montabert-brv-32-spring-pin',
      kind: 'springPin',
    },
    { make: 'Furukawa', model: 'F22', file: 'tapa-furukawa-f22-key-pin-plug', kind: 'keyPinPlug' },
  ],
  burc: [
    {
      make: 'Rammer',
      model: 'E64',
      file: 'pim-rammer-e64-tool-bushing-pin',
      kind: 'toolBushingPin',
    },
    {
      make: 'Rammer',
      model: 'E66',
      file: 'pim-rammer-e66-tool-bushing-pin',
      kind: 'toolBushingPin',
    },
    {
      make: 'Rammer',
      model: 'G80',
      file: 'pim-rammer-g80-tool-bushing-pin',
      kind: 'toolBushingPin',
    },
    {
      make: 'Rammer',
      model: 'S25',
      file: 'pim-rammer-s25-upper-bushing-pin',
      kind: 'upperBushingPin',
    },
    {
      make: 'Rammer',
      model: 'S84',
      file: 'pim-rammer-s84-tool-bushing-pin',
      kind: 'toolBushingPin',
    },
    { make: 'MTB', model: '210', file: 'pim-mtb-210-tool-bushing-pin', kind: 'toolBushingPin' },
    {
      make: 'MTB',
      model: '210 II',
      file: 'pim-mtb-210-ii-tool-bushing-pin',
      kind: 'toolBushingPin',
    },
    {
      make: 'MTB',
      model: '210 II',
      file: 'tapa-mtb-210-ii-tool-bushing-pin-plug',
      kind: 'toolBushingPinPlug',
    },
    {
      make: 'MTB',
      model: '210 II',
      file: 'pim-mtb-210-ii-upper-bushing-pin-no1',
      kind: 'upperBushingPin',
      variant: 'no1',
    },
    {
      make: 'MTB',
      model: '210 II',
      file: 'pim-mtb-210-ii-upper-bushing-pin-no2',
      kind: 'upperBushingPin',
      variant: 'no2',
    },
    {
      make: 'Krupp',
      model: 'HM 720',
      file: 'pim-krupp-hm-720-tool-upper-pin',
      kind: 'toolUpperPin',
      variant: 'oldType',
    },
    {
      make: 'Soosan',
      model: 'SB121 TS-P',
      file: 'pim-soosan-sb121-ts-p-tool-bushing-pin',
      kind: 'toolBushingPin',
    },
    {
      make: 'Montabert',
      model: 'BRH 501',
      file: 'pim-montabert-brh-501-tool-bushing-pin',
      kind: 'toolBushingPin',
    },
    {
      make: 'Montabert',
      model: 'BRH 501',
      file: 'tapa-montabert-brh-501-tool-bushing-pin-plug',
      kind: 'toolBushingPinPlug',
    },
    {
      make: 'Montabert',
      model: 'BRV 32',
      file: 'pim-montabert-brv-32-tool-bushing-pin',
      kind: 'toolBushingPin',
    },
    {
      make: 'Montabert',
      model: 'BRV 32',
      file: 'pim-montabert-brv-32-tool-bushing-pin-retainer',
      kind: 'toolBushingPinRetainer',
    },
    {
      make: 'Furukawa',
      model: 'F22',
      file: 'pim-furukawa-f22-tool-bushing-pin',
      kind: 'toolBushingPin',
    },
    {
      make: 'Furukawa',
      model: 'F22',
      file: 'tapa-furukawa-f22-tool-bushing-pin-plug',
      kind: 'toolBushingPinPlug',
    },
    {
      make: 'Furukawa',
      model: 'F22',
      file: 'pim-furukawa-f22-upper-bushing-pin',
      kind: 'upperBushingPin',
    },
    {
      make: 'Furukawa',
      model: 'F22',
      file: 'tapa-furukawa-f22-upper-bushing-pin-plug',
      kind: 'upperBushingPinPlug',
    },
    {
      make: 'Furukawa',
      model: 'HB20G',
      file: 'pim-furukawa-hb20g-tool-bushing-pin',
      kind: 'toolBushingPin',
    },
    {
      make: 'Furukawa',
      model: 'HB30G',
      file: 'pim-furukawa-hb30g-key-upper-pin',
      kind: 'keyUpperPin',
    },
    {
      make: 'Furukawa',
      model: 'HB30G',
      file: 'pim-furukawa-hb30g-tool-bushing-pin',
      kind: 'toolBushingPin',
    },
  ],
  'asinma-plakasi': [
    {
      make: 'Rammer',
      model: 'E64',
      file: 'asinma-rammer-e64-all-round-wear-plate',
      kind: 'allRoundWearPlate',
    },
    { make: 'Rammer', model: 'E64', file: 'takoz-rammer-e64-side-buffer', kind: 'sideBuffer' },
    { make: 'Rammer', model: 'E64', file: 'takoz-rammer-e64-top-buffer', kind: 'topBuffer' },
    { make: 'Rammer', model: 'E66', file: 'takoz-rammer-e66-top-buffer', kind: 'topBuffer' },
    {
      make: 'Rammer',
      model: 'E66',
      file: 'takoz-rammer-e66-top-buffer-city',
      kind: 'topBuffer',
      variant: 'city',
    },
    { make: 'Rammer', model: 'G80', file: 'takoz-rammer-g80-side-buffer', kind: 'sideBuffer' },
    {
      make: 'Rammer',
      model: 'G80',
      file: 'takoz-rammer-g80-side-buffer-pu',
      kind: 'sideBuffer',
      variant: 'pu',
    },
    { make: 'Rammer', model: 'G80', file: 'takoz-rammer-g80-top-buffer', kind: 'topBuffer' },
    {
      make: 'Rammer',
      model: 'G80',
      file: 'asinma-rammer-g80-wear-plate-no1',
      kind: 'wearPlate',
      variant: 'no1',
    },
    {
      make: 'Rammer',
      model: 'G80',
      file: 'asinma-rammer-g80-wear-plate-no2',
      kind: 'wearPlate',
      variant: 'no2',
    },
    {
      make: 'Rammer',
      model: 'G80',
      file: 'asinma-rammer-g80-wear-plate-no3',
      kind: 'wearPlate',
      variant: 'no3',
    },
    {
      make: 'Rammer',
      model: 'G80',
      file: 'asinma-rammer-g80-wear-plate-no4',
      kind: 'wearPlate',
      variant: 'no4',
    },
    { make: 'Rammer', model: 'S84', file: 'takoz-rammer-s84-side-buffer', kind: 'sideBuffer' },
    {
      make: 'Rammer',
      model: 'S84',
      file: 'takoz-rammer-s84-top-buffer-pu',
      kind: 'topBuffer',
      variant: 'pu',
    },
    {
      make: 'Rammer',
      model: 'S84',
      file: 'takoz-rammer-s84-top-buffer-rubber',
      kind: 'topBuffer',
      variant: 'rubber',
    },
    { make: 'MTB', model: '150', file: 'takoz-mtb-150-side-buffer', kind: 'sideBuffer' },
    { make: 'MTB', model: '150', file: 'takoz-mtb-150-top-buffer', kind: 'topBuffer' },
    { make: 'MTB', model: '150', file: 'takoz-mtb-150-top-buffer-plate', kind: 'topBufferPlate' },
    { make: 'MTB', model: '210', file: 'takoz-mtb-210-top-buffer', kind: 'topBuffer' },
    { make: 'MTB', model: '210', file: 'takoz-mtb-210-top-buffer-plate', kind: 'topBufferPlate' },
    {
      make: 'MTB',
      model: '210',
      file: 'takoz-mtb-210-top-buffer-plate-new-type',
      kind: 'topBufferPlate',
      variant: 'newType',
    },
    { make: 'MTB', model: '210 II', file: 'takoz-mtb-210-ii-bottom-buffer', kind: 'bottomBuffer' },
    {
      make: 'MTB',
      model: '210 II',
      file: 'asinma-mtb-210-ii-front-wear-plate',
      kind: 'frontWearPlate',
    },
    { make: 'MTB', model: '210 II', file: 'takoz-mtb-210-ii-side-buffer', kind: 'sideBuffer' },
    {
      make: 'MTB',
      model: '210 II',
      file: 'asinma-mtb-210-ii-side-wear-plate',
      kind: 'sideWearPlate',
    },
    {
      make: 'MTB',
      model: '210 II',
      file: 'asinma-mtb-210-ii-top-wear-plate',
      kind: 'topWearPlate',
    },
    {
      make: 'Krupp',
      model: 'HM 1500',
      file: 'takoz-krupp-hm-1500-side-buffer',
      kind: 'sideBuffer',
    },
    {
      make: 'Krupp',
      model: 'HM 1500',
      file: 'asinma-krupp-hm-1500-side-wear-plate',
      kind: 'sideWearPlate',
    },
    { make: 'Krupp', model: 'HM 1500', file: 'takoz-krupp-hm-1500-top-buffer', kind: 'topBuffer' },
    { make: 'Krupp', model: 'HM 560', file: 'takoz-krupp-hm-560-side-buffer', kind: 'sideBuffer' },
    { make: 'Krupp', model: 'HM 560', file: 'takoz-krupp-hm-560-top-buffer', kind: 'topBuffer' },
    { make: 'Krupp', model: 'HM 720', file: 'takoz-krupp-hm-720-side-buffer', kind: 'sideBuffer' },
    { make: 'Krupp', model: 'HM 720', file: 'takoz-krupp-hm-720-top-buffer', kind: 'topBuffer' },
    { make: 'Krupp', model: 'HM 960', file: 'takoz-krupp-hm-960-side-buffer', kind: 'sideBuffer' },
    { make: 'Krupp', model: 'HM 960', file: 'takoz-krupp-hm-960-top-buffer', kind: 'topBuffer' },
    {
      make: 'Soosan',
      model: 'SB121 TS-P',
      file: 'takoz-soosan-sb121-ts-p-bottom-buffer',
      kind: 'bottomBuffer',
    },
    {
      make: 'Soosan',
      model: 'SB121 TS-P',
      file: 'takoz-soosan-sb121-ts-p-bottom-buffer-plate',
      kind: 'bottomBufferPlate',
    },
    {
      make: 'Soosan',
      model: 'SB121 TS-P',
      file: 'takoz-soosan-sb121-ts-p-buffer-guide',
      kind: 'bufferGuide',
    },
    {
      make: 'Soosan',
      model: 'SB121 TS-P',
      file: 'takoz-soosan-sb121-ts-p-top-buffer',
      kind: 'topBuffer',
    },
    {
      make: 'Soosan',
      model: 'SB121 TS-P',
      file: 'takoz-soosan-sb121-ts-p-top-buffer-type-y',
      kind: 'topBuffer',
      variant: 'typeY',
    },
    {
      make: 'Montabert',
      model: 'BRH 501',
      file: 'takoz-montabert-brh-501-side-buffer',
      kind: 'sideBuffer',
    },
    {
      make: 'Montabert',
      model: 'BRH 501',
      file: 'takoz-montabert-brh-501-top-buffer',
      kind: 'topBuffer',
    },
    {
      make: 'Montabert',
      model: 'BRV 32',
      file: 'takoz-montabert-brv-32-side-buffer',
      kind: 'sideBuffer',
    },
    {
      make: 'Furukawa',
      model: 'F22',
      file: 'takoz-furukawa-f22-buffer-guide',
      kind: 'bufferGuide',
    },
    { make: 'Furukawa', model: 'F22', file: 'takoz-furukawa-f22-top-buffer', kind: 'topBuffer' },
    {
      make: 'Furukawa',
      model: 'HB20G',
      file: 'takoz-furukawa-hb20g-side-buffer',
      kind: 'sideBuffer',
    },
    {
      make: 'Furukawa',
      model: 'HB30G',
      file: 'takoz-furukawa-hb30g-side-buffer',
      kind: 'sideBuffer',
    },
  ],
  akumulator: [
    {
      make: 'MTB',
      model: '210 II',
      file: 'pim-mtb-210-ii-accumulator-dowel',
      kind: 'accumulatorDowel',
    },
  ],
};
