import type { Dict } from '../types';

/* ═══════════════════════════════════════════════════════════════════════
   Dictionary — TR / EN
   Ported from public/dict.jsx. Kısa, duygusal, teknik detaysız.
═══════════════════════════════════════════════════════════════════════ */

export const DICT: Dict = {
  tr: {
    nav: {
      products: 'Ürünler',
      craft: 'İmalathanemiz',
      industries: 'Sektörler',
      contact: 'İletişim',
      cta: 'Teklif Al',
    },
    hero: {
      eyebrow: 'Kocaeli · 1999',
      title1: 'Kırıcıyı ayakta',
      title2: 'tutan parçalar.',
      sub: 'Keski, piston, burç, sızdırmazlık. Her biri kendi atölyemizde, kendi ellerimizle.',
      cta: 'Teklif Al',
      ctaSecondary: 'Ürünlere bak',
      stats: [
        { n: '26',    l: 'Yıl deneyim' },
        { n: '40+',   l: 'Marka uyumu' },
        { n: '1000+', l: 'Parça çeşidi' },
        { n: '24s',   l: 'Teklif süresi' },
      ],
    },
    products: {
      eyebrow: 'Ürün Aileleri',
      title: 'Basit dört kalem.\nHer kırıcının ihtiyacı.',
      aside: 'Her parça kendi tezgâhında, kendi malzemesiyle. Değiştirilemeyen tek şey: özen.',
      items: [
        { name: 'Keski',  desc: 'Kırıcının ucu. Toprakla, taşla, betonla ilk temas noktası.', img: '/photos/chisel-stock.jpeg' },
        { name: 'Piston', desc: 'Darbenin kaynağı. Yüksek frekansla çalışır, yılmaz durur.', img: '/photos/cnc-machining.jpeg' },
        { name: 'Burç',   desc: 'Sessiz kahraman. Piston ile keski arasında dengeyi kurar.', img: '/photos/saw-machine.jpeg' },
        { name: 'Kit',    desc: 'Sızdırmazlık ve bağlantı parçaları. Ayrıntıların tümü.', img: '/photos/workshop-overview.jpeg' },
      ],
    },
    chisels: {
      eyebrow: 'Uçlar',
      title: 'Her zemin için bir keski.',
      aside: 'Sivriden yassıya, asfalttan kayaya. İmalatımızdan çıkan uçların bir seçkisi.',
      items: [
        { name: 'Sivri uç',       desc: 'Sert zemin: granit, beton, sert kaya', img: '', video: '' },
        { name: 'Yassı keski',    desc: 'Yüzey işleri, beton kırma',             img: '', video: '' },
        { name: 'Konik keski',    desc: 'Genel kullanım, çok amaçlı',            img: '', video: '' },
        { name: 'Piramit uç',     desc: 'Agresif darbe, ağır iş',                img: '', video: '' },
        { name: 'Asfalt keskisi', desc: 'Yol bakım, asfalt sökümü',              img: '', video: '' },
        { name: 'Özel ölçü',      desc: 'Özel ekipmanlar için, sipariş üzerine', img: '', video: '' },
      ],
    },
    stock: {
      eyebrow: 'Stok',
      title: 'Tezgâhta ne varsa.',
      aside: 'Kırıcının bakım gününde ihtiyacın olan her parça — işlenmiş, kontrol edilmiş, sevkiyata hazır.',
      items: [
        { name: 'Piston',       desc: 'Darbenin kaynağı, hassas tolerans',    img: '', video: '' },
        { name: 'Burç',         desc: 'Piston yatakları, aşınmaya dayanıklı', img: '', video: '' },
        { name: 'Sızdırmazlık', desc: 'Yağ ve toz conta setleri',             img: '', video: '' },
        { name: 'Silindir',     desc: 'Dış ve iç gövde, yüksek dayanım',      img: '', video: '' },
        { name: 'Tamir kiti',   desc: 'Değiştirilen parçaların tümü',         img: '', video: '' },
        { name: 'Özel talep',   desc: 'Marka/model uyumlu, hızlı temin',      img: '', video: '' },
      ],
    },
    atolye: {
      eyebrow: 'Atölye',
      title: 'Üretimin nefes aldığı yer.',
      aside: 'Bir tezgâhtan diğerine, bir elden diğerine. Her parça buradan geçer.',
      items: [
        { name: 'CNC tezgâhı',    desc: 'Hassas tolerans işçiliği',        img: '', video: '' },
        { name: 'Forj',           desc: 'Sıcak şekillendirme',             img: '', video: '' },
        { name: 'Isıl işlem',     desc: 'Sertleştirme fırını',             img: '', video: '' },
        { name: 'Taşlama',        desc: 'Yüzey ve silindirik taşlama',     img: '', video: '' },
        { name: 'Kalite kontrol', desc: 'Her parça elle denetimden geçer', img: '', video: '' },
        { name: 'Paketleme',      desc: 'Sevkiyat öncesi son adım',        img: '', video: '' },
      ],
    },
    craft: {
      eyebrow: 'İmalathanemiz',
      title: 'Zanaat ellerde yaşar.',
      body: 'Yirmi altı yıl önce bir hayalle başladık. Bugün aynı çatı altında, aynı özenle, aynı titizlikle devam ediyoruz. Üretim hattımız değil — imalathanemiz.',
    },
    industries: {
      eyebrow: 'Kimler İçin',
      title: 'İşini yapanın yanında.',
      aside: 'Türkiye\'nin her köşesinde, kazıdan ocağa, yoldan yıkıma — sahada çalışan her kırıcıya.',
      items: [
        { name: 'İnşaat',     desc: 'Temel kazıdan yıkıma' },
        { name: 'Madencilik', desc: 'Ocağın derininde' },
        { name: 'Kariyer',    desc: 'Kayayla iş görenler' },
        { name: 'Yol',        desc: 'Altyapı ve yenileme' },
      ],
      marquee: [
        '1999\'dan beri Kocaeli\'de',
        'Yirmi altı yıllık zanaat',
        'Kendi atölyemizde, kendi ellerimizle',
        'Kırk üzeri kırıcı markası',
        'Bin üzeri parça çeşidi',
        'Yirmi dört saat içinde teklif',
        'Sahanın yanında',
      ],
    },
    contact: {
      eyebrow: 'İletişim',
      title: 'Bir mesaj, bir cevap.',
      sub: 'Formunu doldur, yirmi dört saat içinde dönelim.',
      fields: {
        name: 'Ad Soyad',
        company: 'Firma',
        email: 'E-posta',
        phone: 'Telefon',
        message: 'Ne arıyorsun?',
      },
      kvkk: 'KVKK Aydınlatma Metni\'ni okudum, iletişim için bilgilerimin işlenmesini kabul ediyorum.',
      submit: 'Gönder',
      sending: 'Gönderiliyor…',
      success: 'Aldık. En kısa sürede dönüyoruz.',
      error: 'Bir sorun oldu. +90 531 669 37 34\'ü arayabilirsin.',
      address: 'Uzunçiftlik Mah. Sadun Atığ Cad. No:112/A\nKartepe · Kocaeli',
      phoneLabel: 'Telefon',
      emailLabel: 'E-posta',
      hoursLabel: 'Çalışma',
      hours: 'Pzt–Cmt · 08:00–18:00',
    },
    footer: {
      brand: 'Kervan Heat',
      tag: 'Kocaeli · 1999',
      rights: '© 2026 Kervan Isıl İşlem. Tüm hakları saklıdır.',
      kvkk: 'KVKK',
    },
  },

  en: {
    nav: {
      products: 'Products',
      craft: 'Our Workshop',
      industries: 'Industries',
      contact: 'Contact',
      cta: 'Get a Quote',
    },
    hero: {
      eyebrow: 'Kocaeli · Since 1999',
      title1: 'Parts that keep',
      title2: 'the hammer running.',
      sub: 'Chisels, pistons, bushings, seals. Each one made in our workshop, by hand.',
      cta: 'Get a Quote',
      ctaSecondary: 'See products',
      stats: [
        { n: '26',    l: 'Years of craft' },
        { n: '40+',   l: 'Hammer brands' },
        { n: '1000+', l: 'Parts shipped' },
        { n: '24h',   l: 'Quote turnaround' },
      ],
    },
    products: {
      eyebrow: 'Product Families',
      title: 'Four simple things.\nWhat every hammer needs.',
      aside: 'Every part on its own bench, with its own steel. The one thing that never changes: care.',
      items: [
        { name: 'Chisel',  desc: 'The point of the hammer. First contact with earth, rock, concrete.', img: '/photos/chisel-stock.jpeg' },
        { name: 'Piston',  desc: 'The source of the strike. High frequency. Doesn\'t flinch.', img: '/photos/cnc-machining.jpeg' },
        { name: 'Bushing', desc: 'The quiet hero. Holds the balance between piston and chisel.', img: '/photos/saw-machine.jpeg' },
        { name: 'Kit',     desc: 'Seals and fasteners. All the small things.', img: '/photos/workshop-overview.jpeg' },
      ],
    },
    chisels: {
      eyebrow: 'Chisels',
      title: 'A tip for every ground.',
      aside: 'From moil to flat, asphalt to rock. A selection from our shop floor.',
      items: [
        { name: 'Moil point',     desc: 'Hard ground: granite, concrete, hard rock', img: '', video: '' },
        { name: 'Flat chisel',    desc: 'Surface work, concrete breaking',           img: '', video: '' },
        { name: 'Tapered',        desc: 'General purpose, versatile',                img: '', video: '' },
        { name: 'Pyramid',        desc: 'Aggressive impact, heavy duty',             img: '', video: '' },
        { name: 'Asphalt cutter', desc: 'Road maintenance, pavement removal',        img: '', video: '' },
        { name: 'Custom size',    desc: 'Special rigs, made to order',               img: '', video: '' },
      ],
    },
    stock: {
      eyebrow: 'In Stock',
      title: 'Whatever is on the bench.',
      aside: 'Every part you need on a service day — machined, inspected, ready to ship.',
      items: [
        { name: 'Piston',        desc: 'Source of the strike, tight tolerance', img: '', video: '' },
        { name: 'Bushing',       desc: 'Piston seats, wear resistant',          img: '', video: '' },
        { name: 'Seals',         desc: 'Oil and dust seal sets',                img: '', video: '' },
        { name: 'Cylinder',      desc: 'Outer and inner body, high durability', img: '', video: '' },
        { name: 'Repair kit',    desc: 'Every consumable in one set',           img: '', video: '' },
        { name: 'Special order', desc: 'Brand/model matched, quick lead time',  img: '', video: '' },
      ],
    },
    atolye: {
      eyebrow: 'Workshop',
      title: 'Where production breathes.',
      aside: 'From one bench to the next, one hand to the next. Every part passes through here.',
      items: [
        { name: 'CNC machining',   desc: 'Tight-tolerance work',        img: '', video: '' },
        { name: 'Forge',           desc: 'Hot forming',                 img: '', video: '' },
        { name: 'Heat treatment',  desc: 'Hardening furnace',           img: '', video: '' },
        { name: 'Grinding',        desc: 'Surface & cylindrical grind', img: '', video: '' },
        { name: 'Quality control', desc: 'Every part hand-inspected',   img: '', video: '' },
        { name: 'Packaging',       desc: 'Final step before shipping',  img: '', video: '' },
      ],
    },
    craft: {
      eyebrow: 'Our Workshop',
      title: 'Craft lives in hands.',
      body: 'We started twenty-six years ago with one idea. Today we keep going under the same roof, with the same care, the same attention. It is not a production line — it is our workshop.',
    },
    industries: {
      eyebrow: 'Who We Serve',
      title: 'Beside the people doing the work.',
      aside: 'Across Turkey — from trench to pit, from roadwork to demolition — with every crew running a breaker.',
      items: [
        { name: 'Construction', desc: 'From foundation to demolition' },
        { name: 'Mining',       desc: 'Deep in the pit' },
        { name: 'Quarry',       desc: 'Working with stone' },
        { name: 'Roads',        desc: 'Infrastructure & renewal' },
      ],
      marquee: [
        'In Kocaeli since 1999',
        'Twenty-six years of craft',
        'In our own workshop, by our own hands',
        'Forty-plus hammer brands',
        'A thousand-plus part variants',
        'Quotes within twenty-four hours',
        'Beside the field',
      ],
    },
    contact: {
      eyebrow: 'Contact',
      title: 'One message, one answer.',
      sub: 'Fill the form. We will come back within twenty-four hours.',
      fields: {
        name: 'Name',
        company: 'Company',
        email: 'Email',
        phone: 'Phone',
        message: 'What are you looking for?',
      },
      kvkk: 'I have read the privacy notice and consent to my information being processed for contact.',
      submit: 'Send',
      sending: 'Sending…',
      success: 'Got it. We will be in touch soon.',
      error: 'Something went wrong. You can call +90 531 669 37 34.',
      address: 'Uzunçiftlik Mah. Sadun Atığ Cad. No:112/A\nKartepe · Kocaeli · Türkiye',
      phoneLabel: 'Phone',
      emailLabel: 'Email',
      hoursLabel: 'Hours',
      hours: 'Mon–Sat · 08:00–18:00',
    },
    footer: {
      brand: 'Kervan Heat',
      tag: 'Kocaeli · Since 1999',
      rights: '© 2026 Kervan Heat Treatment. All rights reserved.',
      kvkk: 'Privacy',
    },
  },
};
