import type { Dict } from '../types';

/* ═══════════════════════════════════════════════════════════════════════
   Dictionary — TR (default) / EN.
   Long-scroll Home + detail routes. Brand: Kervan Breaker.
═══════════════════════════════════════════════════════════════════════ */

export const DICT: Dict = {
  tr: {
    nav: {
      products: 'Ürünler',
      atolye: 'Atölye',
      craft: 'İmalathanemiz',
      industries: 'Sektörler',
      contact: 'İletişim',
      tech: 'Teknik Bilgiler',
      cta: 'Teklif Al',
      home: 'Kervan Breaker — anasayfa',
      menu: 'Menü',
      language: 'Dil',
    },
    opening: {
      scroll: 'kaydır',
    },
    hero: {
      eyebrow: 'Kocaeli · 2004',
      title1: 'Kırıcıyı ayakta',
      title2: 'tutan parçalar.',
      sub: 'Keski, piston, burç, sızdırmazlık. Her biri kendi atölyemizde, kendi ellerimizle.',
      cta: 'Teklif Al',
      ctaSecondary: 'Ürünlere bak',
      stats: [
        { n: '22', l: 'Yıl deneyim' },
        { n: '40+', l: 'Marka uyumu' },
        { n: '1000+', l: 'Parça çeşidi' },
        { n: '24s', l: 'Teklif süresi' },
      ],
    },
    products: {
      eyebrow: 'Ürün Aileleri',
      title: 'Basit dört kalem.\nHer kırıcının ihtiyacı.',
      aside: 'Her parça kendi tezgâhında, kendi malzemesiyle. Değiştirilemeyen tek şey: özen.',
      items: [
        {
          slug: 'keski',
          name: 'Keski',
          desc: 'Kırıcının ucu. Toprakla, taşla, betonla ilk temas noktası.',
          img: '/photos/uclar/uclar-yard.jpeg',
        },
        {
          slug: 'piston',
          name: 'Piston',
          desc: 'Darbenin kaynağı. Yüksek frekansla çalışır, yılmaz durur.',
          img: '/photos/pistonlar/pistons-stack.jpeg',
        },
        {
          slug: 'burc',
          name: 'Burç',
          desc: 'Sessiz kahraman. Piston ile keski arasında dengeyi kurar.',
          img: '/photos/burclar/burclar-raf.jpeg',
        },
        {
          slug: 'tamir-kiti',
          name: 'Kit',
          desc: 'Sızdırmazlık ve bağlantı parçaları. Ayrıntıların tümü.',
          img: '/photos/kit/seal-kit.jpeg',
        },
      ],
    },
    productsPage: {
      eyebrow: 'Ürünler',
      title: 'Dokuz aile.\nHer kırıcının ihtiyacı.',
      aside:
        'Sahanın gerçek sarfı — keski uçtan saplamasına, alt gövdeden tamir kitine. Marka model paritesi koruyarak tedarik ediyoruz.',
    },
    chisels: {
      eyebrow: 'Uçlar',
      title: 'Her zemin için bir keski.',
      aside: 'Sivriden yassıya, asfalttan kayaya. İmalatımızdan çıkan uçların bir seçkisi.',
      items: [
        { name: 'Sivri uç', desc: 'Sert zemin: granit, beton, sert kaya', img: '', video: '' },
        { name: 'Yassı keski', desc: 'Yüzey işleri, beton kırma', img: '', video: '' },
        { name: 'Konik keski', desc: 'Genel kullanım, çok amaçlı', img: '', video: '' },
        { name: 'Piramit uç', desc: 'Agresif darbe, ağır iş', img: '', video: '' },
        { name: 'Asfalt keskisi', desc: 'Yol bakım, asfalt sökümü', img: '', video: '' },
        { name: 'Özel ölçü', desc: 'Özel ekipmanlar için, sipariş üzerine', img: '', video: '' },
      ],
    },
    stock: {
      eyebrow: 'Stok',
      title: 'Tezgâhta ne varsa.',
      aside:
        'Kırıcının bakım gününde ihtiyacın olan her parça — işlenmiş, kontrol edilmiş, sevkiyata hazır.',
      items: [
        { name: 'Piston', desc: 'Darbenin kaynağı, hassas tolerans', img: '', video: '' },
        { name: 'Burç', desc: 'Piston yatakları, aşınmaya dayanıklı', img: '', video: '' },
        { name: 'Sızdırmazlık', desc: 'Yağ ve toz conta setleri', img: '', video: '' },
        { name: 'Silindir', desc: 'Dış ve iç gövde, yüksek dayanım', img: '', video: '' },
        { name: 'Tamir kiti', desc: 'Değiştirilen parçaların tümü', img: '', video: '' },
        { name: 'Özel talep', desc: 'Marka/model uyumlu, hızlı temin', img: '', video: '' },
      ],
    },
    atolye: {
      eyebrow: 'Atölyeden',
      title: 'Üretimin nefes aldığı yer.',
      aside: 'Bir tezgâhtan diğerine, bir elden diğerine. Her parça buradan geçer.',
      items: [
        {
          name: 'Atölye',
          desc: 'Aynı çatı altında, aynı eller',
          img: '/videos/atolye/workshop-01.jpg',
          video: '/videos/atolye/workshop-01.mp4',
        },
        {
          name: 'Bant testere',
          desc: 'Çubuk kesim, dövme stoğu',
          img: '/videos/atolye/yard-01.jpg',
          video: '/videos/atolye/yard-01.mp4',
        },
        {
          name: 'CNC işleme',
          desc: 'Hassas tolerans, kıvılcım altında',
          img: '/photos/atolye/cnc-machining.jpeg',
        },
        {
          name: 'Isıl işlem',
          desc: 'Sertleştirme fırını, lot kontrolü',
          img: '/videos/atolye/furnace-01.jpg',
          video: '/videos/atolye/furnace-01.mp4',
        },
        {
          name: 'Stok rafları',
          desc: 'Numaralı raflarda, hazır',
          img: '/videos/stok/shelves-01.jpg',
          video: '/videos/stok/shelves-01.mp4',
        },
        {
          name: 'Piston stoğu',
          desc: 'Marka uyumlu, sevkiyata hazır',
          img: '/videos/stok/pistons-02.jpg',
          video: '/videos/stok/pistons-02.mp4',
        },
        {
          name: 'Hazır kasalar',
          desc: 'Dış gövdeler, kontrol edilmiş',
          img: '/videos/stok/casings-01.jpg',
          video: '/videos/stok/casings-01.mp4',
        },
      ],
    },
    craft: {
      eyebrow: 'İmalathanemiz',
      title: 'Zanaat ellerde yaşar.',
      body: "Kartepe'de küçük bir tezgâhla başladık. Bugün hâlâ aynı çatı altındayız — aynı eller, aynı özen, aynı titizlik. Burası bir üretim hattı değil; bu bir imalathane.",
    },
    brands: {
      eyebrow: 'Uyumlu Markalar',
      title: 'Kırk üzeri kırıcı markası — kendi parçamızı eşleriz.',
      items: [
        'Atlas Copco',
        'Furukawa',
        'Soosan',
        'Montabert',
        'Indeco',
        'Rammer',
        'Epiroc',
        'Sandvik',
        'NPK',
        'Toku',
        'Kobelco',
        'Hanwoo',
        'Krupp',
        'D&A',
      ],
      pageTitle: 'On beşten fazla kırıcı markası.',
      pageAside:
        'Atlas Copco · Furukawa · Soosan · Indeco · NPK · Rammer · Montabert · Epiroc · Sandvik · Toku · Kobelco · Hanwoo · Krupp · D&A. Aradığınız model listemizde değilse, parça çizimi paylaşın — eşleşme bulalım.',
    },
    industries: {
      eyebrow: 'Kimler İçin',
      title: 'İşini yapanın yanında.',
      aside:
        'Bina yıkımından maden ocağına, taş kesiminden yol bakımına — sahada kırıcı çalıştıran herkes için.',
      items: [
        { name: 'İnşaat', desc: 'Temel, yıkım, kentsel dönüşüm' },
        { name: 'Madencilik', desc: 'Yer altı işletmeleri, sert kaya' },
        { name: 'Taş Ocağı', desc: 'Granit, mermer, agrega' },
        { name: 'Altyapı', desc: 'Yol bakımı, kanalizasyon, demiryolu' },
      ],
      marquee: [
        "2004'ten beri Kocaeli'de",
        'Yirmi iki yıllık zanaat',
        'Kendi atölyemizde, kendi ellerimizle',
        'Kırk üzeri kırıcı markası',
        'Bin üzeri parça çeşidi',
        'Yirmi dört saat içinde teklif',
        'Sahanın yanında',
      ],
    },
    exports: {
      eyebrow: 'İhracat Ağı',
      title: '{count}+ ülkeye yol aldık.',
      aside:
        "Kocaeli'den çıkıp Avrupa, MENA, Orta Asya ve Amerika'ya yol alan parçalar. Sürükle, döndür — noktaya dokun, hangi şehir olduğunu gör.",
    },
    techUi: {
      eyebrow: 'Teknik Bilgiler',
      title: 'Teknik bilgiler.',
      loginTitle: 'Giriş',
      passwordLabel: 'Parola',
      submit: 'Giriş yap',
      sending: 'Giriliyor…',
      wrong: 'Parola hatalı.',
      notConfigured: 'Giriş şu anda kapalı (yapılandırılmamış).',
      error: 'Bir hata oluştu. Tekrar deneyin.',
      logout: 'Çıkış yap',
      loading: 'Yükleniyor…',
    },
    catalogUi: {
      tabsLabel: 'Teknik bilgi bölümleri',
      tabGeneral: 'Genel',
      tabCatalog: 'Uç Kataloğu',
      title: 'Uç kataloğu',
      sub: 'VEGA kırıcı uçları. Elindeki ucu ölçerek, ya da model ve parça no ile bul.',
      loading: 'Katalog yükleniyor…',
      errorUnauthorized: 'Oturum sona erdi. Lütfen tekrar giriş yapın.',
      errorNotConfigured: 'Katalog henüz yapılandırılmamış.',
      errorEmpty: 'Katalog verisi bulunamadı.',
      errorGeneric: 'Katalog yüklenemedi.',
      retry: 'Tekrar dene',
      searchLabel: 'Ara',
      searchPlaceholder: 'Model, parça no veya kırıcı (ör. S 52, VT0100232)',
      brandLabel: 'Marka',
      brandAll: 'Tüm markalar',
      tipLabel: 'Uç tipi',
      hideLow: 'Düşük güvenli satırları gizle',
      measureTitle: 'Ölçüyle bul',
      measureHint:
        'Bildiğin ölçüleri yaz, gerisini boş bırak. Virgül veya nokta kullanabilirsin. Boy sorulmaz: aşınmış ucun boyu bir şey söylemez.',
      measureDia: 'Çap Ø (mm)',
      measureKeyThk: 'Kama kalınlığı (mm)',
      measureKeyCount: 'Kama',
      keyAny: 'Fark etmez',
      keySingle: 'Tek',
      keyDouble: 'Çift',
      measureBackToSlot: 'Arka uç → kanal başı (mm)',
      measureSlotLen: 'Kama kanalı boyu (mm)',
      measureRearDia: 'Arka çıkıntı Ø (mm)',
      featTitle: 'Özellikler',
      featHint:
        'Çizimden okunan özellikler. Bilgisi çıkarılamayan uçlar listede kalır; ton tahmini uç çapından hesaplanır.',
      featAny: 'Fark etmez',
      featYes: 'Var',
      featNo: 'Yok',
      featRear: 'Arka çıkıntı',
      featSlot: 'Kanal sonu',
      featSlotTapered: 'Konik (açılı)',
      featSlotRounded: 'Yuvarlak (açısız)',
      featAngle: 'Uç açısı',
      featAngled: 'Açılı',
      featNotAngled: 'Açısız',
      featTons: 'Makine ağırlığı (ton)',
      tolLabel: 'Tolerans',
      clear: 'Temizle',
      resultsCount: 'Sonuç: {n}',
      groupMatch: 'Eşleşenler',
      groupMaybe: 'Eşleşebilir (katalogda bazı ölçüler yok)',
      groupMaybeHint: 'Girdiğin ölçülerden bazıları bu uçlar için katalogda yazılmamış.',
      emptyResults: 'Sonuç yok.',
      emptyHint:
        '±{t} mm içinde uç bulunamadı. Toleransı artırmayı veya bir ölçüyü boş bırakmayı dene.',
      more: 'Daha fazla göster',
      details: 'Detay',
      hideDetails: 'Detayı gizle',
      drawingTitle: 'Teknik resim',
      drawingAlt: '{model} teknik resmi: yandan görünüş, ölçüler mm',
      drawingLoading: 'Teknik resim yükleniyor…',
      drawingError: 'Teknik resim yüklenemedi.',
      compare: 'Karşılaştır',
      compareTitle: 'Karşılaştırma',
      compareClose: 'Karşılaştırmayı kapat',
      compareMax: 'Karşılaştırma için en fazla {n} uç seçilebilir.',
      compareRemove: 'Karşılaştırmadan çıkar',
      invalidNumber: 'Sayı girin (ör. 52,5).',
      copyLabel: 'Parça numarasını kopyala',
      tipLabels: {
        chisel: 'Chisel (yassı)',
        moil: 'Moil Point (sivri)',
        blunt: 'Blunt Tool (künt)',
        pyramid: 'Pyramid (piramit)',
      },
      copy: 'Kopyala',
      copied: 'Kopyalandı',
      warnBadge: 'Katalog sayfasından doğrulayın',
      missing: 'katalogda yok',
      fDia: 'Çap Ø',
      fCollar: 'Yaka çapı',
      fKey: 'Kama',
      fKeyThk: 'Kama kalınlığı',
      fBackToSlot: 'Arka uç → kanal başı',
      fSlotLen: 'Kama kanalı boyu',
      fRearDia: 'Arka çıkıntı Ø',
      fRearStep: 'Arka çıkıntı',
      fSlotEnd: 'Kanal sonu',
      fTipAngle: 'Uç açısı',
      fCarrier: 'Tahmini makine ağırlığı',
      carrierValue: '{a}–{b} ton',
      carrierNote:
        'Uç çapından çıkarılan kaba aralık (Furukawa, NPK, Soosan, Indeco, Atlas Copco, Montabert katalog ve bayi verileri). Aynı çapta kırıcıya göre değişir; kırıcı modeliyle doğrulayın.',
      useTitle: 'Uç tipleri ne için?',
      useNote:
        'Genel rehber. Üretici ve bayi kaynakları birbirinden biraz farklı söyleyebilir; kırıcınızın üreticisinin uç önerisi önceliklidir.',
      useRock: 'Taş / malzeme',
      useWhere: 'Nerede',
      useWatch: 'Dikkat',
      guideTitle: 'Uç nereden kırılırsa garantiye girer?',
      guideCauses: 'Sık nedenler',
      guideWarranty: 'Garanti yaklaşımı',
      guideSources: 'Kaynaklar',
      guideDefectTitle: 'Kusur mu, hatalı kullanım mı? (kırık yüzeyinden)',
      guideClaimTitle: 'Garanti talebinde istenecekler',
      useTips: {
        chisel: {
          rock: 'Orta sert, tabakalı taş; beton, asfalt',
          where: 'Hendek, kazı, betonarme yıkım',
          watch: 'Sert kayada moil kadar nüfuz etmez.',
        },
        moil: {
          rock: 'Sert ve homojen olmayan taş, betonarme',
          where: 'Ocak, yıkım, ikincil kırma, toplu kazı',
          watch: 'Yumuşak veya elastik malzemede sıkışır; sıkışınca kaldıraç yapmayın, kırılır.',
        },
        blunt: {
          rock: 'Sert, aşındırıcı taş (granit vb.), cüruf, iri blok',
          where: 'Yalnızca ikincil kırma (iri blokları parçalama)',
          watch: 'Nüfuz etmez; hassas veya yönlü işte uygun değil.',
        },
        pyramid: {
          rock: 'Çok sert taş (granit, kuvarsit), kalın beton',
          where: 'Ocak, ağır yıkım, ikincil kırma',
          watch:
            'Bazı üreticiler moil ile aynı sınıfta sayar; kaynaklar yumuşaklık konusunda ayrışır.',
        },
      },
      fLength: 'Boy',
      fWeight: 'Ağırlık',
      fTips: 'Uç tipleri',
      fFits: 'Uyumlu kırıcılar',
      fPartNos: 'VEGA parça no',
      fOther: 'Diğer ölçüler',
      fNotes: 'Notlar',
      fSource: 'Kaynak',
      sourceFmt: 'Katalog s. {c} (PDF s. {p})',
      byType: 'Uç tipine göre',
      matchedVia: 'Eşleşme: {name} (uyumlu listesinden)',
      phoneticHint: 'Yazım tam tutmadı, benzer okunuşlara göre bulundu.',
      twinsLabel: 'Aynı ölçüde {n} model daha',
      twinsHint: 'Katalog ölçüleri birebir aynı; tek teklif hepsine uyar. Boy farklı olabilir.',
      equivalents: 'Aynı ölçülü uçlar',
      equivalentsHint: 'Katalog ölçüsü aynı, yine de kontrol edin.',
      conflictWarn: '{name} için katalogda {n} farklı uç ölçüsü var. Ölçerek doğrulayın.',
      conflictMeasure: 'Ölçüyle bul',
      popularBadge: 'Çok satan',
      popularBadge2: 'Yaygın',
      popularTwin: 'Çok satan bir uçla aynı ölçü',
      popularOnly: 'Sadece Türkiye’de yaygın uçlar',
      popularStatus: '{n} yaygın uç işaretli',
      popularNote:
        'Ölçüler ayıramadığında Türkiye’de yaygın uçlar öne alınır; belirgin ölçü farkını örtmez.',
      measureOptional: '(isteğe bağlı)',
      likelyTitle: 'En olası uç',
      likelyPct: '%{p} olasılık',
      likelyModels: 'Aynı uç: {models}',
      likelyRunner: 'İkinci aday: {model} (%{p})',
      likelyOutsideTol: 'Seçili ±{t} mm toleransın dışında; aşınma payıyla en yakın bu.',
      likelyMoreMeasure: 'Emin olmak için bir ölçü daha alın.',
      nextMeasure: 'Şimdi şunu ölçün: {field}',
      nextMeasureHint: 'Aday ölçü sayısı ~{a} → ~{b}',
      chipLegend:
        'Yeşil: ölçüm payı içinde · Turuncu: aşınmaya uygun fark · Kırmızı: açıklanamayan fark',
      chipUnknown: 'katalogda yok',
      fieldNames: {
        dia: 'Çap',
        keyThk: 'Kama kalınlığı',
        backToSlot: 'Arka uç → kanal başı',
        slotLen: 'Kama kanalı boyu',
        rearDia: 'Arka çıkıntı Ø',
        length: 'Boy',
        keyCount: 'Kama sayısı (Tek/Çift)',
      },
      partNoClash: 'Bu parça no katalogda farklı ölçülü başka uçta da geçiyor: {models}',
      partNoBroken: 'Parça no biçimi bozuk görünüyor (VT + 7 hane bekleniyor)',
      diffLabels: {
        dia: 'Ø',
        keyThk: 'Kama',
        backToSlot: 'Arka uç→kanal',
        slotLen: 'Kanal boyu',
        rearDia: 'Arka çıkıntı Ø',
        length: 'Boy',
      },
      qualityLabels: {
        geometry_missing: 'Boy ve ağırlık katalogda yok',
        columns_shifted_weight_missing: 'Katalogda ağırlık sütunu kaymış, ağırlık yok',
        dia_length_swapped: 'Katalogda çap ile boy yer değiştirmiş',
        length_unparsed: 'Boy okunamadı',
        weight_unparsed: 'Ağırlık okunamadı',
        kama_unknown: 'Kama tipi belirsiz',
        key_thickness_gt_diameter: 'Kama kalınlığı çaptan büyük görünüyor',
        rear_shoulder_gt_diameter: 'Arka çıkıntı çaptan büyük görünüyor',
        slot_beyond_length: 'Kanal ölçüleri boydan uzun görünüyor',
        weight_implausible_for_dia_length: 'Ağırlık, çap ve boya göre tutarsız olabilir',
      },
      flagLabels: {
        key_thickness: 'Kama kalınlığı belirsiz',
        drawing_body_dia: 'Çizimdeki gövde çapı belirsiz',
        diameter_table: 'Çap tablosu belirsiz',
        key_count: 'Kama sayısı belirsiz',
        back_dia: 'Arka çıkıntı Ø belirsiz',
        part_nos: 'Parça no belirsiz',
      },
    },
    productionPage: {
      eyebrow: 'Üretim & Kalite',
      title: 'Çelik, ısıl işlem, kontrol.',
      body: 'Bir kırıcı parçasının ömrü iki şeye bağlıdır: doğru alaşım ve doğru ısıl işlem. Biz ikisini de kendi disiplinimizle yürütürüz.',
      metallurgyHeading: 'Metallurji',
      metallurgyBody:
        'TTT/CCT eğrileri üzerinde çalışıyoruz — soğuma hızının iç yapıyı nasıl yazdığını biliyoruz. Sertlik ve dayanım, her parti için lot başı ölçülür.',
      heatHeading: 'Isıl İşlem Entegrasyonu',
      heatBody:
        'Her parça kendi tesisimizde — kontrollü atmosfer pit-tip fırınlarda — sertleştirme ve temperleme süreçlerinden geçer. Aynı çatı, aynı disiplin.',
      heatLink: 'Isıl işlem hattımızı tanıyın →',
      materialsHeading: 'Standart Alaşımlar',
      materials: ['42CrMo', '42CrMoA', 'Diğer alaşımlar — talep üzerine'],
    },
    aboutPage: {
      eyebrow: 'Hakkımızda',
      title: 'Aynı çatı, iki disiplin.',
      body: "Kervan Makina, Kartepe / Kocaeli'de hem fason ısıl işlem (kervanheat.com) hem de hidrolik kırıcı yedek parça üretimi yapan bir aile şirketi. Aynı tezgâhta, aynı ellerle. Bu sitede hidrolik kırıcı yedek parça vitrinimiz var — ısıl işlem hizmeti için kervanheat.com'a bakın.",
      company: 'Kervan Isıl İşlem San. Tic. Ltd. Şti.',
      location: 'Kartepe · Kocaeli',
    },
    productDetail: {
      materialsLabel: 'Malzeme',
      sizesLabel: 'Ölçüler',
      brandFitsLabel: 'Marka Uyumluluk',
      sizesNote: 'Marka, model ve seri numarası belirtin — uygun ölçüyü size yönelik teyit ederiz.',
      backLink: '← Tüm ürünler',
      quoteCta: 'Bu parça için teklif al',
      notFound: 'Bu ürün bulunamadı.',
      notFoundCta: 'Tüm ürünlere dön',
    },
    contact: {
      eyebrow: 'İletişim',
      title: 'Bir mesaj, bir cevap.',
      sub: 'Formunu doldur, yirmi dört saat içinde dönelim.',
      fields: {
        name: 'Ad Soyad',
        company: 'Firma',
        email: 'E-posta',
        phone: 'Telefon',
        message: 'Ne arıyorsun?',
      },
      submit: 'Gönder',
      sending: 'Gönderiliyor…',
      success: 'Aldık. En kısa sürede dönüyoruz.',
      error: "Bir sorun oldu. +90 531 669 37 34'ü arayabilirsin.",
      address: 'Uzunçiftlik Mah. Sadun Atığ Cad. No:112/A\nKartepe · Kocaeli',
      phoneLabel: 'Telefon',
      whatsappLabel: 'WhatsApp',
      emailLabel: 'E-posta',
      instagramLabel: 'Instagram',
      hoursLabel: 'Çalışma',
      hours: 'Pzt–Cmt · 08:00–18:00',
      quotePrefix: 'Teklif talebi —',
    },
    notFound: {
      title: 'Sayfa bulunamadı.',
      body: 'Aradığınız sayfa taşınmış veya hiç var olmamış olabilir.',
      cta: 'Anasayfaya dön',
    },
    footer: {
      brand: 'Kervan Breaker',
      tag: 'Kocaeli · 2004',
      rights: '© 2026 Kervan Isıl İşlem San. Tic. Ltd. Şti. Tüm hakları saklıdır.',
      kvkk: 'KVKK',
    },
  },

  en: {
    nav: {
      products: 'Products',
      atolye: 'Workshop',
      craft: 'Our Story',
      industries: 'Industries',
      contact: 'Contact',
      tech: 'Technical Info',
      cta: 'Get a Quote',
      home: 'Kervan Breaker — home',
      menu: 'Menu',
      language: 'Language',
    },
    opening: {
      scroll: 'scroll',
    },
    hero: {
      eyebrow: 'Kocaeli · Since 2004',
      title1: 'Parts that keep',
      title2: 'the hammer running.',
      sub: 'Chisels, pistons, bushings, seals. Each one made in our workshop, by hand.',
      cta: 'Get a Quote',
      ctaSecondary: 'See products',
      stats: [
        { n: '22', l: 'Years of craft' },
        { n: '40+', l: 'Hammer brands' },
        { n: '1000+', l: 'Parts shipped' },
        { n: '24h', l: 'Quote turnaround' },
      ],
    },
    products: {
      eyebrow: 'Product Families',
      title: 'Four simple things.\nWhat every hammer needs.',
      aside:
        'Every part on its own bench, with its own steel. The one thing that never changes: care.',
      items: [
        {
          slug: 'keski',
          name: 'Chisel',
          desc: 'The point of the hammer. First contact with earth, rock, concrete.',
          img: '/photos/uclar/uclar-yard.jpeg',
        },
        {
          slug: 'piston',
          name: 'Piston',
          desc: "The source of the strike. High frequency. Doesn't flinch.",
          img: '/photos/pistonlar/pistons-stack.jpeg',
        },
        {
          slug: 'burc',
          name: 'Bushing',
          desc: 'The quiet hero. Holds the balance between piston and chisel.',
          img: '/photos/burclar/burclar-raf.jpeg',
        },
        {
          slug: 'tamir-kiti',
          name: 'Kit',
          desc: 'Seals and fasteners. All the small things.',
          img: '/photos/kit/seal-kit.jpeg',
        },
      ],
    },
    productsPage: {
      eyebrow: 'Products',
      title: 'Nine families.\nWhat every hammer needs.',
      aside:
        'The real consumables of the field — from chisel tip to side stud, lower housing to repair kit. Supplied with brand-model parity preserved.',
    },
    chisels: {
      eyebrow: 'Chisels',
      title: 'A tip for every ground.',
      aside: 'From moil to flat, asphalt to rock. A selection from our shop floor.',
      items: [
        {
          name: 'Moil point',
          desc: 'Hard ground: granite, concrete, hard rock',
          img: '',
          video: '',
        },
        { name: 'Flat chisel', desc: 'Surface work, concrete breaking', img: '', video: '' },
        { name: 'Tapered', desc: 'General purpose, versatile', img: '', video: '' },
        { name: 'Pyramid', desc: 'Aggressive impact, heavy duty', img: '', video: '' },
        { name: 'Asphalt cutter', desc: 'Road maintenance, pavement removal', img: '', video: '' },
        { name: 'Custom size', desc: 'Special rigs, made to order', img: '', video: '' },
      ],
    },
    stock: {
      eyebrow: 'In Stock',
      title: 'Whatever is on the bench.',
      aside: 'Every part you need on a service day — machined, inspected, ready to ship.',
      items: [
        { name: 'Piston', desc: 'Source of the strike, tight tolerance', img: '', video: '' },
        { name: 'Bushing', desc: 'Piston seats, wear resistant', img: '', video: '' },
        { name: 'Seals', desc: 'Oil and dust seal sets', img: '', video: '' },
        { name: 'Cylinder', desc: 'Outer and inner body, high durability', img: '', video: '' },
        { name: 'Repair kit', desc: 'Every consumable in one set', img: '', video: '' },
        { name: 'Special order', desc: 'Brand/model matched, quick lead time', img: '', video: '' },
      ],
    },
    atolye: {
      eyebrow: 'From the workshop',
      title: 'Where production breathes.',
      aside: 'From one bench to the next, one hand to the next. Every part passes through here.',
      items: [
        {
          name: 'Workshop',
          desc: 'Under the same roof, by the same hands',
          img: '/videos/atolye/workshop-01.jpg',
          video: '/videos/atolye/workshop-01.mp4',
        },
        {
          name: 'Band saw',
          desc: 'Bar cutting, forged stock',
          img: '/videos/atolye/yard-01.jpg',
          video: '/videos/atolye/yard-01.mp4',
        },
        {
          name: 'CNC machining',
          desc: 'Tight tolerance, under sparks',
          img: '/photos/atolye/cnc-machining.jpeg',
        },
        {
          name: 'Heat treatment',
          desc: 'Hardening furnace, lot inspection',
          img: '/videos/atolye/furnace-01.jpg',
          video: '/videos/atolye/furnace-01.mp4',
        },
        {
          name: 'Stock shelves',
          desc: 'Numbered, ready to ship',
          img: '/videos/stok/shelves-01.jpg',
          video: '/videos/stok/shelves-01.mp4',
        },
        {
          name: 'Piston stock',
          desc: 'Brand-matched, on the floor',
          img: '/videos/stok/pistons-02.jpg',
          video: '/videos/stok/pistons-02.mp4',
        },
        {
          name: 'Casings ready',
          desc: 'Outer bodies, inspected',
          img: '/videos/stok/casings-01.jpg',
          video: '/videos/stok/casings-01.mp4',
        },
      ],
    },
    craft: {
      eyebrow: 'Our Workshop',
      title: 'Craft lives in hands.',
      body: 'We started in Kartepe with a single bench. Today we are still under the same roof — same hands, same care, same attention. This is not a production line; this is a workshop.',
    },
    brands: {
      eyebrow: 'Compatible Brands',
      title: 'Forty-plus hammer brands — we match the part.',
      items: [
        'Atlas Copco',
        'Furukawa',
        'Soosan',
        'Montabert',
        'Indeco',
        'Rammer',
        'Epiroc',
        'Sandvik',
        'NPK',
        'Toku',
        'Kobelco',
        'Hanwoo',
        'Krupp',
        'D&A',
      ],
      pageTitle: 'Fifteen-plus hammer brands.',
      pageAside:
        "Atlas Copco · Furukawa · Soosan · Indeco · NPK · Rammer · Montabert · Epiroc · Sandvik · Toku · Kobelco · Hanwoo · Krupp · D&A. If your model isn't listed, send the drawing — we will find a match.",
    },
    industries: {
      eyebrow: 'Who We Serve',
      title: 'Beside the people doing the work.',
      aside:
        'From building demolition to mine pit, stone quarry to roadworks — for every crew running a breaker on site.',
      items: [
        { name: 'Construction', desc: 'Foundations, demolition, urban renewal' },
        { name: 'Mining', desc: 'Underground operations, hard rock' },
        { name: 'Quarry', desc: 'Granite, marble, aggregate' },
        { name: 'Infrastructure', desc: 'Road repair, sewer, rail' },
      ],
      marquee: [
        'In Kocaeli since 2004',
        'Twenty-two years of craft',
        'In our own workshop, by our own hands',
        'Forty-plus hammer brands',
        'A thousand-plus part variants',
        'Quotes within twenty-four hours',
        'Beside the field',
      ],
    },
    exports: {
      eyebrow: 'Export Reach',
      title: 'Shipped to {count}+ countries.',
      aside:
        'Parts shipped from Kocaeli to Europe, MENA, Central Asia and the Americas. Drag to spin — tap a marker for the city.',
    },
    techUi: {
      eyebrow: 'Technical Info',
      title: 'Technical info.',
      loginTitle: 'Sign in',
      passwordLabel: 'Password',
      submit: 'Sign in',
      sending: 'Signing in…',
      wrong: 'Wrong password.',
      notConfigured: 'Sign-in is currently disabled (not configured).',
      error: 'Something went wrong. Please try again.',
      logout: 'Sign out',
      loading: 'Loading…',
    },
    catalogUi: {
      tabsLabel: 'Technical info sections',
      tabGeneral: 'General',
      tabCatalog: 'Tip catalog',
      title: 'Tip catalog',
      sub: 'VEGA breaker tips. Find a tip by measuring it, or by model and part number.',
      loading: 'Loading catalog…',
      errorUnauthorized: 'Your session ended. Please sign in again.',
      errorNotConfigured: 'The catalog is not configured yet.',
      errorEmpty: 'No catalog data found.',
      errorGeneric: 'Could not load the catalog.',
      retry: 'Try again',
      searchLabel: 'Search',
      searchPlaceholder: 'Model, part no. or breaker (e.g. S 52, VT0100232)',
      brandLabel: 'Brand',
      brandAll: 'All brands',
      tipLabel: 'Tip type',
      hideLow: 'Hide low-confidence rows',
      measureTitle: 'Find by measurement',
      measureHint:
        'Enter the sizes you know and leave the rest empty. Comma or dot both work. Length is not asked: the length of a worn tip tells nothing.',
      measureDia: 'Diameter Ø (mm)',
      measureKeyThk: 'Key thickness (mm)',
      measureKeyCount: 'Key',
      keyAny: 'Any',
      keySingle: 'Single',
      keyDouble: 'Double',
      measureBackToSlot: 'Back end → slot start (mm)',
      measureSlotLen: 'Key slot length (mm)',
      measureRearDia: 'Rear protrusion Ø (mm)',
      featTitle: 'Features',
      featHint:
        'Read from the drawings. Tips whose feature could not be read stay in the list; the tonnage is estimated from the tip diameter.',
      featAny: 'Any',
      featYes: 'Yes',
      featNo: 'No',
      featRear: 'Rear protrusion',
      featSlot: 'Slot end',
      featSlotTapered: 'Tapered (angled)',
      featSlotRounded: 'Rounded (no angle)',
      featAngle: 'Tip angle',
      featAngled: 'Angled',
      featNotAngled: 'Not angled',
      featTons: 'Carrier weight (tonnes)',
      tolLabel: 'Tolerance',
      clear: 'Clear',
      resultsCount: 'Results: {n}',
      groupMatch: 'Matches',
      groupMaybe: 'Possible matches (some sizes missing in the catalog)',
      groupMaybeHint: 'Some of the sizes you entered are not listed for these tips.',
      emptyResults: 'No results.',
      emptyHint: 'No tip within ±{t} mm. Try a larger tolerance or leave a size empty.',
      more: 'Show more',
      details: 'Details',
      hideDetails: 'Hide details',
      drawingTitle: 'Technical drawing',
      drawingAlt: 'Technical drawing of {model}: side view, dimensions in mm',
      drawingLoading: 'Loading technical drawing…',
      drawingError: 'Could not load the technical drawing.',
      compare: 'Compare',
      compareTitle: 'Comparison',
      compareClose: 'Close comparison',
      compareMax: 'You can compare up to {n} tips.',
      compareRemove: 'Remove from comparison',
      invalidNumber: 'Enter a number (e.g. 52.5).',
      copyLabel: 'Copy part number',
      tipLabels: {
        chisel: 'Chisel',
        moil: 'Moil Point',
        blunt: 'Blunt Tool',
        pyramid: 'Pyramid',
      },
      copy: 'Copy',
      copied: 'Copied',
      warnBadge: 'Check against the catalog page',
      missing: 'not in catalog',
      fDia: 'Diameter Ø',
      fCollar: 'Collar diameter',
      fKey: 'Key',
      fKeyThk: 'Key thickness',
      fBackToSlot: 'Back end → slot start',
      fSlotLen: 'Key slot length',
      fRearDia: 'Rear protrusion Ø',
      fRearStep: 'Rear protrusion',
      fSlotEnd: 'Slot end',
      fTipAngle: 'Tip angle',
      fCarrier: 'Estimated carrier weight',
      carrierValue: '{a}–{b} t',
      carrierNote:
        'Rough range from the tip diameter (Furukawa, NPK, Soosan, Indeco, Atlas Copco, Montabert catalogue and dealer data). It varies by breaker at the same diameter; confirm with the breaker model.',
      useTitle: 'What are the tip types for?',
      useNote:
        'General guide. Manufacturer and dealer sources differ a little; the breaker maker’s own tip recommendation comes first.',
      useRock: 'Rock / material',
      useWhere: 'Where',
      useWatch: 'Watch out',
      guideTitle: 'Where a tip breaks: what warranty usually covers',
      guideCauses: 'Usual causes',
      guideWarranty: 'Warranty approach',
      guideSources: 'Sources',
      guideDefectTitle: 'Defect or misuse? (from the fracture face)',
      guideClaimTitle: 'What a warranty claim needs',
      useTips: {
        chisel: {
          rock: 'Medium-hard, layered rock; concrete, asphalt',
          where: 'Trenching, excavation, reinforced-concrete demolition',
          watch: 'Penetrates hard rock less than a moil point.',
        },
        moil: {
          rock: 'Hard, non-homogeneous rock; reinforced concrete',
          where: 'Quarry, demolition, secondary breaking, mass excavation',
          watch: 'Can jam in soft or elastic material; never pry with a stuck tool, it breaks.',
        },
        blunt: {
          rock: 'Hard, abrasive rock (granite etc.), slag, oversize blocks',
          where: 'Secondary breaking only (splitting oversize blocks)',
          watch: 'Does not penetrate; unsuitable for precise or directional work.',
        },
        pyramid: {
          rock: 'Very hard rock (granite, quartzite), thick concrete',
          where: 'Quarry, heavy demolition, secondary breaking',
          watch: 'Some makers class it with the moil point; sources differ on soft ground.',
        },
      },
      fLength: 'Length',
      fWeight: 'Weight',
      fTips: 'Tip types',
      fFits: 'Compatible breakers',
      fPartNos: 'VEGA part no.',
      fOther: 'Other sizes',
      fNotes: 'Notes',
      fSource: 'Source',
      sourceFmt: 'Catalog p. {c} (PDF p. {p})',
      byType: 'By tip type',
      matchedVia: 'Matched: {name} (compatible list)',
      phoneticHint: 'No exact spelling match; found by similar sound.',
      twinsLabel: '{n} more models with the same sizes',
      twinsHint: 'Identical catalog sizes; one quote fits all. Length may differ.',
      equivalents: 'Tips with the same sizes',
      equivalentsHint: 'Same catalog sizes; still check.',
      conflictWarn: 'The catalog lists {n} different tip sizes for {name}. Verify by measuring.',
      conflictMeasure: 'Find by measurement',
      popularBadge: 'Best seller',
      popularBadge2: 'Common',
      popularTwin: 'Same sizes as a best seller',
      popularOnly: 'Only tips common in Turkey',
      popularStatus: '{n} common tips marked',
      popularNote:
        'When sizes cannot tell tips apart, tips common in Turkey come first; never over a clear size difference.',
      measureOptional: '(optional)',
      likelyTitle: 'Most likely tip',
      likelyPct: '{p}% likely',
      likelyModels: 'Same tip: {models}',
      likelyRunner: 'Runner-up: {model} ({p}%)',
      likelyOutsideTol: 'Outside the selected ±{t} mm tolerance; closest once wear is allowed for.',
      likelyMoreMeasure: 'Take one more measurement to be sure.',
      nextMeasure: 'Measure next: {field}',
      nextMeasureHint: 'Candidate sizes ~{a} → ~{b}',
      chipLegend:
        'Green: within measuring error · Amber: differs the way wear does · Red: unexplained difference',
      chipUnknown: 'not in catalog',
      fieldNames: {
        dia: 'Diameter',
        keyThk: 'Key thickness',
        backToSlot: 'Back end → slot start',
        slotLen: 'Key slot length',
        rearDia: 'Rear protrusion Ø',
        length: 'Length',
        keyCount: 'Key count (single/double)',
      },
      partNoClash: 'This part number is also listed for a tip with different sizes: {models}',
      partNoBroken: 'Part number looks malformed (expected VT + 7 digits)',
      diffLabels: {
        dia: 'Ø',
        keyThk: 'Key',
        backToSlot: 'Back→slot',
        slotLen: 'Slot length',
        rearDia: 'Rear Ø',
        length: 'Length',
      },
      qualityLabels: {
        geometry_missing: 'Length and weight missing in the catalog',
        columns_shifted_weight_missing: 'Weight column shifted in the catalog, weight missing',
        dia_length_swapped: 'Diameter and length swapped in the catalog',
        length_unparsed: 'Length could not be read',
        weight_unparsed: 'Weight could not be read',
        kama_unknown: 'Key type unclear',
        key_thickness_gt_diameter: 'Key thickness looks larger than the diameter',
        rear_shoulder_gt_diameter: 'Rear protrusion looks larger than the diameter',
        slot_beyond_length: 'Slot sizes look longer than the tip',
        weight_implausible_for_dia_length: 'Weight may not fit the diameter and length',
      },
      flagLabels: {
        key_thickness: 'Key thickness unclear',
        drawing_body_dia: 'Body diameter in the drawing unclear',
        diameter_table: 'Diameter table unclear',
        key_count: 'Key count unclear',
        back_dia: 'Rear protrusion Ø unclear',
        part_nos: 'Part number unclear',
      },
    },
    productionPage: {
      eyebrow: 'Production & Quality',
      title: 'Steel, heat treatment, inspection.',
      body: 'A breaker part lives or dies on two things: the right alloy and the right heat treatment. We run both under our own discipline.',
      metallurgyHeading: 'Metallurgy',
      metallurgyBody:
        'We work on TTT/CCT curves — we know how cooling rate writes the microstructure. Hardness and yield are measured per lot, every batch.',
      heatHeading: 'Heat Treatment Integration',
      heatBody:
        'Every part is hardened and tempered in our own controlled-atmosphere pit furnaces. Same roof, same discipline.',
      heatLink: 'See our heat treatment line →',
      materialsHeading: 'Standard Alloys',
      materials: ['42CrMo', '42CrMoA', 'Other alloys on request'],
    },
    aboutPage: {
      eyebrow: 'About',
      title: 'One roof, two disciplines.',
      body: 'Kervan Makina is a family business in Kartepe / Kocaeli running both contract heat treatment (kervanheat.com) and hydraulic breaker spare-part production. Same bench, same hands. This site is the breaker-parts catalogue — for heat treatment service, see kervanheat.com.',
      company: 'Kervan Isıl İşlem San. Tic. Ltd. Şti.',
      location: 'Kartepe · Kocaeli · Türkiye',
    },
    productDetail: {
      materialsLabel: 'Material',
      sizesLabel: 'Sizes',
      brandFitsLabel: 'Brand Fit',
      sizesNote: 'Tell us the brand, model and serial — we will confirm the matching size for you.',
      backLink: '← All products',
      quoteCta: 'Get a quote for this part',
      notFound: 'Product not found.',
      notFoundCta: 'Back to all products',
    },
    contact: {
      eyebrow: 'Contact',
      title: 'One message, one answer.',
      sub: 'Fill the form. We will come back within twenty-four hours.',
      fields: {
        name: 'Name',
        company: 'Company',
        email: 'Email',
        phone: 'Phone',
        message: 'What are you looking for?',
      },
      submit: 'Send',
      sending: 'Sending…',
      success: 'Got it. We will be in touch soon.',
      error: 'Something went wrong. You can call +90 531 669 37 34.',
      address: 'Uzunçiftlik Mah. Sadun Atığ Cad. No:112/A\nKartepe · Kocaeli · Türkiye',
      phoneLabel: 'Phone',
      whatsappLabel: 'WhatsApp',
      emailLabel: 'Email',
      instagramLabel: 'Instagram',
      hoursLabel: 'Hours',
      hours: 'Mon–Sat · 08:00–18:00',
      quotePrefix: 'Quote request —',
    },
    notFound: {
      title: 'Page not found.',
      body: 'The page you are looking for may have moved or never existed.',
      cta: 'Back to home',
    },
    footer: {
      brand: 'Kervan Breaker',
      tag: 'Kocaeli · Since 2004',
      rights: '© 2026 Kervan Isıl İşlem San. Tic. Ltd. Şti. All rights reserved.',
      kvkk: 'Privacy',
    },
  },
};
