import type { Dict } from '../types';

export const DICT: Dict = {
  tr: {
    nav: {
      home: 'Anasayfa',
      products: 'Ürünler',
      brands: 'Marka Uyumluluk',
      production: 'Üretim & Kalite',
      about: 'Hakkımızda',
      contact: 'İletişim',
      cta: 'Teklif Al',
    },
    hero: {
      eyebrow: 'Kartepe · Kocaeli',
      title1: 'Hidrolik kırıcı',
      title2: 'yedek parçaları.',
      sub: 'Keski, piston, burç, tie rod, tamir kiti — fabrika çıkışlı kalite, kendi ısıl işlem hattımızdan geçmiş, on beşten fazla marka uyumlu.',
      cta: 'Teklif Al',
      ctaSecondary: 'Ürünler',
    },
    productsPage: {
      eyebrow: 'Ürünler',
      title: 'Dokuz aile.\nHer kırıcının ihtiyacı.',
      aside: 'Sahanın gerçek sarfı — keski uçtan saplamasına, alt gövdeden tamir kitine. Marka model paritesi koruyarak tedarik ediyoruz.',
    },
    brandsPage: {
      eyebrow: 'Marka Uyumluluk',
      title: 'On beşten fazla kırıcı markası.',
      aside: 'Atlas Copco · Furukawa · Soosan · Indeco · NPK · Rammer · Montabert · Epiroc · Sandvik · Toku · Kobelco · Hanwoo · Krupp · D&A. Aradığınız model listemizde değilse, parça çizimi paylaşın — eşleşme bulalım.',
    },
    productionPage: {
      eyebrow: 'Üretim & Kalite',
      title: 'Çelik, ısıl işlem, kontrol.',
      body: 'Bir kırıcı parçasının ömrü iki şeye bağlıdır: doğru alaşım ve doğru ısıl işlem. Biz ikisini de kendi disiplinimizle yürütürüz.',
      metallurgyHeading: 'Metallurji',
      metallurgyBody: 'TTT/CCT eğrileri üzerinde çalışıyoruz — soğuma hızının iç yapıyı nasıl yazdığını biliyoruz. Sertlik ve dayanım, her parti için lot başı ölçülür.',
      heatHeading: 'Isıl İşlem Entegrasyonu',
      heatBody: 'Her parça kendi tesisimizde — kontrollü atmosfer pit-tip fırınlarda — sertleştirme, temperleme ve gerektiğinde sementasyon süreçlerinden geçer. Aynı çatı, aynı disiplin.',
      heatLink: 'Isıl işlem hattımızı tanıyın →',
      materialsHeading: 'Standart Alaşımlar',
      materials: ['42CrMo', '42CrMoA', 'Diğer alaşımlar — talep üzerine'],
    },
    aboutPage: {
      eyebrow: 'Hakkımızda',
      title: 'Aynı çatı, iki disiplin.',
      body: 'Kervan Makina, Kartepe / Kocaeli\'de hem fason ısıl işlem (kervanheat.com) hem de hidrolik kırıcı yedek parça üretimi yapan bir aile şirketi. Aynı tezgâhta, aynı ellerle. Bu sitede sadece kırıcı parça vitrinimiz var — ısıl işlem hizmeti için kervanheat.com\'a bakın.',
      company: 'Kervan Isıl İşlem San. Tic. Ltd. Şti.',
      location: 'Kartepe · Kocaeli',
    },
    contactPage: {
      eyebrow: 'İletişim',
      title: 'Bir mesaj, bir cevap.',
      sub: 'Aradığınız parçanın markasını, modelini ve adedini paylaşın — yirmi dört saat içinde dönelim.',
      fields: {
        name: 'Ad Soyad',
        company: 'Firma',
        email: 'E-posta',
        phone: 'Telefon',
        message: 'Hangi marka / model, hangi parça, kaç adet?',
      },
      kvkk: 'KVKK Aydınlatma Metni\'ni okudum, iletişim için bilgilerimin işlenmesini kabul ediyorum.',
      submit: 'Gönder',
      sending: 'Gönderiliyor…',
      success: 'Aldık. En kısa sürede dönüyoruz.',
      error: 'Bir sorun oldu. +90 531 669 37 34\'ü arayabilirsin.',
      address: 'Kartepe · Kocaeli',
      phoneLabel: 'Telefon',
      emailLabel: 'E-posta',
      instagramLabel: 'Instagram',
      hoursLabel: 'Çalışma',
      hours: 'Pzt–Cmt · 08:00–18:00',
      quotePrefix: 'Teklif talebi —',
    },
    qualityTeaser: {
      eyebrow: 'Üretim & Kalite',
      title: 'Çelik bizde başlar, fırından geçer, ölçüm masasında biter.',
      body: '42CrMo / 42CrMoA standart alaşımı, kendi pit-tip fırınımızda sertleştirme + temperleme, OES spektrometre ile lot başı malzeme analizi.',
      link: 'Üretim & kalite süreci →',
    },
    brandStrip: {
      eyebrow: 'Marka Uyumluluk',
      title: 'On beşten fazla kırıcı markası.',
    },
    productDetail: {
      materialsLabel: 'Malzeme',
      sizesLabel: 'Ölçüler',
      brandFitsLabel: 'Marka Uyumluluk',
      sizesNote: 'Marka, model ve seri numarası belirtin — uygun ölçüyü size yönelik teyit ederiz.',
      backLink: '← Tüm ürünler',
      quoteCta: 'Bu parça için teklif al',
      notFound: 'Bu ürün bulunamadı.',
      notFoundCta: 'Tüm ürünlere dön',
    },
    footer: {
      brand: 'Kervan Breaker',
      tag: 'Kartepe · Kocaeli',
      rights: '© 2026 Kervan Isıl İşlem San. Tic. Ltd. Şti. Tüm hakları saklıdır.',
      kvkk: 'KVKK',
    },
    notFound: {
      title: 'Sayfa bulunamadı.',
      body: 'Aradığınız sayfa taşınmış veya hiç var olmamış olabilir.',
      cta: 'Anasayfaya dön',
    },
  },

  en: {
    nav: {
      home: 'Home',
      products: 'Products',
      brands: 'Brand Fit',
      production: 'Production & Quality',
      about: 'About',
      contact: 'Contact',
      cta: 'Get a Quote',
    },
    hero: {
      eyebrow: 'Kartepe · Kocaeli',
      title1: 'Hydraulic breaker',
      title2: 'spare parts.',
      sub: 'Chisels, pistons, bushings, tie rods, repair kits — factory-grade quality, run through our own heat treatment line, fits fifteen-plus hammer brands.',
      cta: 'Get a Quote',
      ctaSecondary: 'Products',
    },
    productsPage: {
      eyebrow: 'Products',
      title: 'Nine families.\nWhat every hammer needs.',
      aside: 'The real consumables of the field — from chisel tip to side stud, lower housing to repair kit. We supply with brand-model parity preserved.',
    },
    brandsPage: {
      eyebrow: 'Brand Fit',
      title: 'Fifteen-plus hammer brands.',
      aside: 'Atlas Copco · Furukawa · Soosan · Indeco · NPK · Rammer · Montabert · Epiroc · Sandvik · Toku · Kobelco · Hanwoo · Krupp · D&A. If your model isn\'t listed, send the drawing — we will find a match.',
    },
    productionPage: {
      eyebrow: 'Production & Quality',
      title: 'Steel, heat treatment, inspection.',
      body: 'A breaker part lives or dies on two things: the right alloy and the right heat treatment. We run both under our own discipline.',
      metallurgyHeading: 'Metallurgy',
      metallurgyBody: 'We work on TTT/CCT curves — we know how cooling rate writes the microstructure. Hardness and yield are measured per lot, every batch.',
      heatHeading: 'Heat Treatment Integration',
      heatBody: 'Every part is hardened, tempered and (where required) carburized in our own controlled-atmosphere pit furnaces. Same roof, same discipline.',
      heatLink: 'See our heat treatment line →',
      materialsHeading: 'Standard Alloys',
      materials: ['42CrMo', '42CrMoA', 'Other alloys on request'],
    },
    aboutPage: {
      eyebrow: 'About',
      title: 'One roof, two disciplines.',
      body: 'Kervan Makina is a family business in Kartepe / Kocaeli running both contract heat treatment (kervanheat.com) and hydraulic breaker spare-part production. Same bench, same hands. This site is the breaker-parts catalogue only — for heat treatment service, see kervanheat.com.',
      company: 'Kervan Isıl İşlem San. Tic. Ltd. Şti.',
      location: 'Kartepe · Kocaeli · Türkiye',
    },
    contactPage: {
      eyebrow: 'Contact',
      title: 'One message, one answer.',
      sub: 'Share the brand, model and quantity of the part you need — we will come back within twenty-four hours.',
      fields: {
        name: 'Name',
        company: 'Company',
        email: 'Email',
        phone: 'Phone',
        message: 'Which brand / model, which part, what quantity?',
      },
      kvkk: 'I have read the privacy notice and consent to my information being processed for contact.',
      submit: 'Send',
      sending: 'Sending…',
      success: 'Got it. We will be in touch soon.',
      error: 'Something went wrong. You can call +90 531 669 37 34.',
      address: 'Kartepe · Kocaeli · Türkiye',
      phoneLabel: 'Phone',
      emailLabel: 'Email',
      instagramLabel: 'Instagram',
      hoursLabel: 'Hours',
      hours: 'Mon–Sat · 08:00–18:00',
      quotePrefix: 'Quote request —',
    },
    qualityTeaser: {
      eyebrow: 'Production & Quality',
      title: 'Steel starts here, passes through the furnace, ends on the inspection bench.',
      body: '42CrMo / 42CrMoA standard alloy, hardening + tempering in our own pit furnace, OES spectrometer analysis per lot.',
      link: 'Production & quality →',
    },
    brandStrip: {
      eyebrow: 'Brand Fit',
      title: 'Fifteen-plus hammer brands.',
    },
    productDetail: {
      materialsLabel: 'Material',
      sizesLabel: 'Sizes',
      brandFitsLabel: 'Brand Fit',
      sizesNote: 'Tell us the brand, model and serial — we will confirm the matching size for you.',
      backLink: '← All products',
      quoteCta: 'Get a quote for this part',
      notFound: 'Product not found.',
      notFoundCta: 'Back to all products',
    },
    footer: {
      brand: 'Kervan Breaker',
      tag: 'Kartepe · Kocaeli',
      rights: '© 2026 Kervan Isıl İşlem San. Tic. Ltd. Şti. All rights reserved.',
      kvkk: 'Privacy',
    },
    notFound: {
      title: 'Page not found.',
      body: 'The page you are looking for may have moved or never existed.',
      cta: 'Back to home',
    },
  },
};
