import type { Dict } from '../types';

/* ═══════════════════════════════════════════════════════════════════════
   Heat-treatment dictionary — TR (default) / EN.
   Kontrollü atmosfer pit-tip fırınlarda fason ısıl işlem.
═══════════════════════════════════════════════════════════════════════ */

export const DICT: Dict = {
  tr: {
    meta: {
      title: 'Kervan Heat — Fason ısıl işlem · Kartepe / Kocaeli',
      description:
        'Kontrollü atmosfer pit-tip fırınlarda fason ısıl işlem. Sertleştirme ve temperleme. 42CrMo, 42CrMoA ve diğer alaşımlar.',
      siteDescription: 'Kontrollü atmosfer pit-tip fırınlarda fason ısıl işlem.',
      service: {
        type: 'Fason ısıl işlem',
        name: 'Fason ısıl işlem',
        description:
          'Kontrollü atmosfer pit-tip fırınlarda sertleştirme ve temperleme. 42CrMo, 42CrMoA ve diğer alaşımlar — kendi ölçüm ve kontrol disiplinimizle.',
        catalogName: 'Isıl işlem hizmetleri',
        offers: [
          {
            name: 'Sertleştirme & Temperleme',
            description: 'Pit-tip fırında ısıtma, kontrollü soğutma, çift potalı temper hattı.',
          },
          {
            name: 'Fason ısıl işlem',
            description: 'Özel alaşım, özel sıcaklık eğrisi, özel parti büyüklüğü.',
          },
        ],
      },
    },
    notFound: {
      eyebrow: '404',
      title: 'Sayfa bulunamadı.',
      body: 'Aradığınız sayfa taşınmış ya da hiç var olmamış olabilir.',
      home: 'Ana sayfaya dön',
    },
    nav: {
      services: 'Hizmetler',
      capacity: 'Teknik Kapasite',
      craft: 'Tesisimiz',
      about: 'Hakkımızda',
      contact: 'İletişim',
      tech: 'Teknik Bilgiler',
      cta: 'Teklif Al',
      home: 'Kervan Heat — ana sayfa',
      menu: 'Menü',
      language: 'Dil',
    },
    sister: {
      tag: 'Kardeş site',
      lead: 'Hidrolik kırıcı yedek parçalarımız ayrı sitemizde:',
      leadShort: 'Kırıcı yedek parçaları:',
      site: 'kervanbreaker.com',
      href: 'https://kervanbreaker.com/',
    },
    hero: {
      eyebrow: 'Kartepe · Kocaeli',
      title1: 'Kontrollü atmosfer pit-tip',
      title2: 'fırınlarda fason ısıl işlem.',
      sub: 'Sertleştirme ve temperleme. 42CrMo, 42CrMoA ve diğer alaşımlar — kendi ölçüm ve kontrol disiplinimizle.',
      cta: 'Teklif Al',
      ctaSecondary: 'Hizmetler',
      stats: [
        { n: '2', l: 'temper potası' },
        { n: 'Ø1200', l: 'mm max çap' },
        { n: '2.5 t', l: 'tek sefer max yük' },
        { n: '42CrMo', l: 'standart alaşım' },
      ],
      film: {
        alt: 'Kartepe tesisimizde kuyu tipi fırın hattı: önde kapağı açık bir fırın, arkada üstünde alev yanan bir fırın',
        caption: 'Fırın hattımız · Kartepe',
        pause: 'Videoyu duraklat',
        play: 'Videoyu oynat',
      },
    },
    services: {
      eyebrow: 'Hizmetler',
      title: 'Üç ana süreç. Tek disiplin.',
      aside: 'Kontrollü atmosfer, ölçülmüş sıcaklık eğrisi, sertlik kontrolü.',
      items: [
        {
          index: '01',
          name: 'Sertleştirme & Temperleme',
          body: 'Pit-tip fırında ısıtma, kontrollü soğutma, ardından temper potasında stres giderimi. İki potalı temper hattı sayesinde aynı gün içinde iki ayrı sıcaklık eğrisi paralel çalışabilir.',
          bullets: [
            'Yağ ve hava soğutma',
            'Çift potalı temper — paralel sıcaklık',
            'Yüzey sertlik kontrolü, lot başı',
          ],
        },
        {
          index: '02',
          name: 'Fason Isıl İşlem',
          body: 'Standart hizmet listesinin dışına çıkan ihtiyaçlar için: özel alaşım, özel sıcaklık eğrisi, özel parti büyüklüğü. Önce numune, sonra seri.',
          bullets: [
            'Diğer alaşımlar — talep üzerine',
            'Özel sıcaklık eğrisi',
            'Numune → seri akış',
          ],
        },
        {
          index: '03',
          name: 'Üretim & Entegrasyon',
          body: 'Hidrolik kırıcı yedek parçalarımızı da kendi tezgahımızda üretir, kendi pit-tip fırınımızda işleriz. Metallurjiyi sadece müşteri parçası için değil, kendi parçamız için de yaşıyoruz.',
          bullets: [
            'Keski, piston, burç, tamir kiti',
            'Aynı tesis, aynı disiplin',
            'Vitrin: kervanbreaker.com',
          ],
        },
      ],
    },
    capacity: {
      eyebrow: 'Teknik Kapasite',
      title: 'Sayılarla atölye.',
      aside: 'Bir bakışta fırın kapasitesi, malzeme yelpazesi ve ölçüm disiplini.',
      items: [
        { value: '2', label: 'Temper potası', note: 'Paralel iki sıcaklık eğrisi' },
        { value: 'Ø1200 mm', label: 'Max parça çapı', note: 'Pit-tip fırın iç ölçüsü' },
        { value: '2.5 ton', label: 'Tek sefer max yük', note: 'Brüt parti ağırlığı' },
        {
          value: '42CrMo · 42CrMoA',
          label: 'Standart alaşımlar',
          note: 'Diğerleri — talep üzerine',
        },
      ],
    },
    techUi: {
      eyebrow: 'Teknik Bilgiler',
      title: 'Teknik bilgiler.',
      loginTitle: 'Giriş',
      passwordLabel: 'Parola',
      submit: 'Giriş yap',
      sending: 'Giriliyor…',
      wrong: 'Parola hatalı.',
      notConfigured: 'Giriş şu anda kapalı (yapılandırılmamış).',
      error: 'Bir hata oluştu. Tekrar deneyin.',
      logout: 'Çıkış yap',
      loading: 'Yükleniyor…',
    },
    craft: {
      eyebrow: 'Tesisimiz',
      title: 'Sıcaklık sabırla yükselir.',
      body: 'Fırın bir tezgâh değil; bir saat. Termokupldan gelen her okuma, atmosferdeki her oksijen seviyesi, eğrideki her dakika — hepsi parçanın iç yapısına yazılır. Burada acele etmek yok; doğru sıcaklık, doğru süre, doğru soğutma. Ve bunun arkasında, on yıllardır aynı tezgâhın başında olan eller.',
      photosLabel: 'Isıl işlem tesisimizden fotoğraflar',
      photos: [
        {
          base: 'tesis-genel-01',
          alt: 'Kervan Isıl İşlem tesisi: tavan vinci, kuyu tipi fırınlar, fikstürler ve şarja hazır burçlar',
          caption: 'Tesisimiz: şarja hazır parçalar ve fikstürler',
        },
        {
          base: 'firin-agzi-01',
          alt: 'Kapağı açık kuyu tipi fırının ağzına yukarıdan bakış; içeride dikey çubuklar',
          caption: 'Fırın ağzı',
        },
        {
          base: 'kontrol-panosu-02',
          alt: 'Duvar boyunca gelen boruların bağlandığı cam kapaklı beyaz dolap; içinde dikey cam tüpler, göstergeler, vanalar ve hortumlar',
          caption: 'Gösterge ve vana dolabı',
        },
        {
          base: 'kapali-firin-01',
          alt: 'Kapağı kapalı kuyu tipi fırın: kapak mekanizması ve üstünde fan motoru; arkada ikinci bir fırın',
          caption: 'Kapalı fırın',
        },
      ],
    },
    about: {
      eyebrow: 'Hakkımızda',
      title: 'Kervan Isıl İşlem San. Tic. Ltd. Şti.',
      body: "Kartepe / Kocaeli'de fason ısıl işlem hizmeti veriyoruz. Türkiye'nin sanayi koridorunun ortasında — gelen parçayı ölçer, işler, kontrol eder ve aynı disiplinle teslim ederiz. Her partinin ardında bir sertlik testi vardır.",
      company: 'Kervan Isıl İşlem San. Tic. Ltd. Şti.',
      location: 'Kartepe · Kocaeli',
    },
    contact: {
      eyebrow: 'İletişim',
      title: 'Bir mesaj, bir cevap.',
      sub: 'Parça çizimini veya malzeme bilgisini paylaş, yirmi dört saat içinde dönüş yapalım.',
      fields: {
        name: 'Ad Soyad',
        company: 'Firma',
        email: 'E-posta',
        phone: 'Telefon',
        message: 'Hangi alaşım, hangi parti büyüklüğü, hangi süreç?',
      },
      submit: 'Gönder',
      sending: 'Gönderiliyor…',
      success: 'Aldık. En kısa sürede dönüyoruz.',
      error: "Bir sorun oldu. +90 531 669 37 34'ü arayabilirsin.",
      address: 'Kartepe · Kocaeli',
      phoneLabel: 'Telefon',
      whatsappLabel: 'WhatsApp',
      emailLabel: 'E-posta',
      instagramLabel: 'Instagram',
      hoursLabel: 'Çalışma',
      hours: 'Pzt–Cmt · 08:00–18:00',
    },
    footer: {
      brand: 'Kervan Heat',
      tag: 'Kartepe · Kocaeli',
      rights: '© 2026 Kervan Isıl İşlem San. Tic. Ltd. Şti. Tüm hakları saklıdır.',
      kvkk: 'KVKK',
      cookies: 'Çerez tercihleri',
    },
    consent: {
      title: 'Çerez tercihi',
      body: 'Reklamlarımızın işe yarayıp yaramadığını ölçmek için Google Ads çerezlerini kullanmak istiyoruz. Bu çerezler yalnızca kabul ederseniz yüklenir ve veriler Google’a (ABD) aktarılır. Reddederseniz site aynen çalışır.',
      accept: 'Kabul et',
      reject: 'Reddet',
      policy: 'Ayrıntılar',
    },
  },

  en: {
    meta: {
      title: 'Kervan Heat — Contract heat treatment · Kartepe / Kocaeli',
      description:
        'Contract heat treatment in controlled-atmosphere pit furnaces. Hardening and tempering. 42CrMo, 42CrMoA and other alloys.',
      siteDescription: 'Contract heat treatment in controlled-atmosphere pit furnaces.',
      service: {
        type: 'Contract heat treatment',
        name: 'Contract heat treatment',
        description:
          'Hardening and tempering in controlled-atmosphere pit furnaces. 42CrMo, 42CrMoA and other alloys — under our own measurement and control discipline.',
        catalogName: 'Heat treatment services',
        offers: [
          {
            name: 'Hardening & Tempering',
            description: 'Heating in a pit furnace, controlled cooling, two-pot tempering line.',
          },
          {
            name: 'Contract heat treatment',
            description: 'Special alloys, special temperature curves, special batch sizes.',
          },
        ],
      },
    },
    notFound: {
      eyebrow: '404',
      title: 'Page not found.',
      body: 'The page you are looking for may have moved or never existed.',
      home: 'Back to the home page',
    },
    nav: {
      services: 'Services',
      capacity: 'Capacity',
      craft: 'Our Plant',
      about: 'About',
      contact: 'Contact',
      tech: 'Technical Info',
      cta: 'Get a Quote',
      home: 'Kervan Heat — home',
      menu: 'Menu',
      language: 'Language',
    },
    sister: {
      tag: 'Sister site',
      lead: 'Our hydraulic breaker spare parts have their own site:',
      leadShort: 'Breaker spare parts:',
      site: 'kervanbreaker.com',
      href: 'https://kervanbreaker.com/en/',
    },
    hero: {
      eyebrow: 'Kartepe · Kocaeli',
      title1: 'Contract heat treatment in',
      title2: 'controlled-atmosphere pit furnaces.',
      sub: 'Hardening and tempering. 42CrMo, 42CrMoA and other alloys — under our own measurement and control discipline.',
      cta: 'Get a Quote',
      ctaSecondary: 'Services',
      stats: [
        { n: '2', l: 'tempering pots' },
        { n: 'Ø1200', l: 'mm max diameter' },
        { n: '2.5 t', l: 'max load per batch' },
        { n: '42CrMo', l: 'standard alloy' },
      ],
      film: {
        alt: 'Pit furnace line at our Kartepe plant: an open furnace in front, and behind it a furnace with a flame burning on top',
        caption: 'Our furnace line · Kartepe',
        pause: 'Pause video',
        play: 'Play video',
      },
    },
    services: {
      eyebrow: 'Services',
      title: 'Three core processes. One discipline.',
      aside: 'Controlled atmosphere, measured temperature curves, hardness checks.',
      items: [
        {
          index: '01',
          name: 'Hardening & Tempering',
          body: 'Heating in a pit furnace, controlled cooling, then stress relief in the tempering pot. With two tempering pots, two distinct temperature curves can run in parallel within the same day.',
          bullets: [
            'Oil and air quench',
            'Two-pot tempering — parallel curves',
            'Surface hardness check, every lot',
          ],
        },
        {
          index: '02',
          name: 'Bespoke Heat Treatment',
          body: 'For requirements outside the standard list: special alloys, special curves, special batch sizes. Sample first, then production run.',
          bullets: [
            'Other alloys on request',
            'Custom temperature curves',
            'Sample → production flow',
          ],
        },
        {
          index: '03',
          name: 'Production & Integration',
          body: 'We also produce hydraulic breaker spare parts on our own benches, run through our own pit furnaces. We live the metallurgy not just for customer parts — for our own parts too.',
          bullets: [
            'Chisel, piston, bushing, repair kit',
            'Same shop, same discipline',
            'Catalogue: kervanbreaker.com',
          ],
        },
      ],
    },
    capacity: {
      eyebrow: 'Capacity',
      title: 'The shop in numbers.',
      aside: 'Furnace capacity, material range and measurement discipline at a glance.',
      items: [
        { value: '2', label: 'Tempering pots', note: 'Two parallel temperature curves' },
        { value: 'Ø1200 mm', label: 'Max part diameter', note: 'Pit furnace inner dimension' },
        { value: '2.5 ton', label: 'Max load per batch', note: 'Gross batch weight' },
        { value: '42CrMo · 42CrMoA', label: 'Standard alloys', note: 'Others on request' },
      ],
    },
    techUi: {
      eyebrow: 'Technical Info',
      title: 'Technical info.',
      loginTitle: 'Sign in',
      passwordLabel: 'Password',
      submit: 'Sign in',
      sending: 'Signing in…',
      wrong: 'Wrong password.',
      notConfigured: 'Sign-in is currently disabled (not configured).',
      error: 'Something went wrong. Please try again.',
      logout: 'Sign out',
      loading: 'Loading…',
    },
    craft: {
      eyebrow: 'Our Plant',
      title: 'Temperature rises with patience.',
      body: 'A furnace is not a bench; it is a clock. Every reading from the thermocouple, every oxygen level in the atmosphere, every minute on the curve — all of it is written into the part. There is no rushing here; the right temperature, the right time, the right cooling. Behind it, the same hands that have stood at the same furnace for decades.',
      photosLabel: 'Photos from our heat treatment plant',
      photos: [
        {
          base: 'tesis-genel-01',
          alt: 'Kervan heat treatment plant: overhead crane, pit furnaces, fixtures and bushings ready to load',
          caption: 'Our plant: parts and fixtures ready to load',
        },
        {
          base: 'firin-agzi-01',
          alt: 'Looking down into an open pit furnace: the mouth with vertical bars inside',
          caption: 'Furnace mouth',
        },
        {
          base: 'kontrol-panosu-02',
          alt: 'White glass-door cabinet fed by pipes running along the wall, with vertical glass tubes, gauges, valves and hoses inside',
          caption: 'Gauge and valve cabinet',
        },
        {
          base: 'kapali-firin-01',
          alt: 'Closed pit furnace: the lid mechanism with the fan motor on top; a second furnace behind',
          caption: 'Closed furnace',
        },
      ],
    },
    about: {
      eyebrow: 'About',
      title: 'Kervan Isıl İşlem San. Tic. Ltd. Şti.',
      body: "We provide contract heat treatment in Kartepe / Kocaeli, in the heart of Türkiye's industrial corridor. We measure the part, run the process, verify the result and ship it back — with the same discipline every time. Behind every batch is a hardness test.",
      company: 'Kervan Isıl İşlem San. Tic. Ltd. Şti.',
      location: 'Kartepe · Kocaeli · Türkiye',
    },
    contact: {
      eyebrow: 'Contact',
      title: 'One message, one answer.',
      sub: 'Share the drawing or material spec — we will come back within twenty-four hours.',
      fields: {
        name: 'Name',
        company: 'Company',
        email: 'Email',
        phone: 'Phone',
        message: 'Which alloy, which batch size, which process?',
      },
      submit: 'Send',
      sending: 'Sending…',
      success: 'Got it. We will be in touch soon.',
      error: 'Something went wrong. You can call +90 531 669 37 34.',
      address: 'Kartepe · Kocaeli · Türkiye',
      phoneLabel: 'Phone',
      whatsappLabel: 'WhatsApp',
      emailLabel: 'Email',
      instagramLabel: 'Instagram',
      hoursLabel: 'Hours',
      hours: 'Mon–Sat · 08:00–18:00',
    },
    footer: {
      brand: 'Kervan Heat',
      tag: 'Kartepe · Kocaeli',
      rights: '© 2026 Kervan Heat Treatment. All rights reserved.',
      kvkk: 'Privacy',
      cookies: 'Cookie settings',
    },
    consent: {
      title: 'Cookie preference',
      body: 'We would like to use Google Ads cookies to measure whether our ads work. They load only if you accept, and the data is transferred to Google (USA). If you decline, the site works exactly the same.',
      accept: 'Accept',
      reject: 'Decline',
      policy: 'Details',
    },
  },
};
